(** * SLA_Chapter4.v — Chapter 4 (equations 4.1–4.69) of the dissertation

    Pedro Yochinori Gushiken, "Adaptação de Segundo Nível como Técnica de
    Estimação de Parâmetros e sua Aplicação ao Controle Adaptativo por
    Modelo de Referência", MSc dissertation, UFRN, 2018 — Chapter 4,
    "Estimação de Parâmetros, Ordem n".

    Background sources consulted for the underlying framework:
      - Z. Han & K. S. Narendra, "New concepts in adaptive control using
        multiple models", IEEE TAC 57(1):78–89, 2012.
      - K. S. Narendra, Y. Wang, W. Chen, "The Rationale for Second Level
        Adaptation", arXiv:1510.04989 (= Narendra et al. 2012/2015).
      - P. Ioannou & J. Sun, "Robust Adaptive Control", 1996 (normalized
        gradient estimator, eqs. 4.12–4.23).
      - G. Chowdhary et al., IJACSP 27(4):280–301, 2013 (concurrent learning,
        the idea behind the forgetting-factor variant, eqs. 4.60–4.69).

    WHAT IS FORMALISED.  Everything in Chapter 4 that is a *mathematical
    statement* rather than a modelling assumption or an asymptotic argument
    invoking Barbalat's lemma / persistency of excitation:

      4.1–4.9    plant transfer function, filters, linear parametrization
                 -> encoded as the hypothesis  z = theta*_p^T phi  (4.8)
      4.10–4.15  first-level regression model, identification error,
                 normalization, e = thetatilde^T phi
      4.16–4.23  normalized gradient law and its Lyapunov function
      4.24–4.30  N first-level models and the dynamics of e_{i,f}
      4.31–4.40  convex combination / virtual model
      4.41–4.45  the alpha* parametrization and invariance of the convex hull
      4.46–4.51  elimination of alpha_N: E_f alpha*_f = -eps_{N,f}
      4.52–4.56  second-level adaptive law and the alphatilde dynamics
      4.57–4.58  Lyapunov analysis of second level adaptation
      4.60–4.67  forgetting factor: M_f, v_f and the SLAFF law
      4.68–4.69  Lyapunov analysis of SLAFF

    Statements 4.1–4.7 and 4.9 fix *notation* for the filters generating phi;
    they carry no content beyond "phi is some differentiable signal and z is
    the linear form theta*^T phi", which is exactly hypothesis [H_param].

    TWO DISCREPANCIES ARE PROVED, not assumed — see [Vb_dyn],
    [Vb_deriv_differs_from_4_58] and [Vb_deriv_can_be_positive] at the end of
    the SLA section, and the comment above [VrF_dyn] for (4.69). *)

Require Import Reals Lra Lia.
Require Import SLA.SLA_Prelim.
Local Open Scope R_scope.

Section Chapter4.

(** ** 4.1–4.9  Plant and linear parametrization

    The plant (4.1)–(4.2) is  G_p(s) = N_p(s)/D_p(s)  of order n and relative
    degree one.  Filtering by a monic Hurwitz Lambda(s) of degree n (4.4) and
    collecting the filtered signals (4.5) produces the regressor
    phi = [phi_1^T phi_2^T]^T generated by (4.6)–(4.7), and the signal
    z = s^n/Lambda(s) y = y + lambda_f^T phi_1 (4.9).

    [d] is the dimension 2n of theta*_p = [a_1..a_n b_1..b_n]^T. *)

Variable d : nat.
Variable phi : R -> nat -> R.          (* the regressor phi(t) in R^d *)
Variable phid : R -> nat -> R.         (* its time derivative           *)
Variable thstar : nat -> R.            (* theta*_p, the true parameters *)
Variable z : R -> R.                   (* the filtered output z(t)      *)

Hypothesis H_phi : forall j, (j < d)%nat -> Deriv (fun t => phi t j) (fun t => phid t j).

(** (4.8): the plant parametrization  z(s) = theta*_p^T phi. *)
Hypothesis H_param : forall t, z t = dot d thstar (phi t).

(** (4.12): n_s^2 = phi^T phi is the normalizing signal and m^2 = 1 + n_s^2. *)
Definition msq (t : R) : R := 1 + dot d (phi t) (phi t).

Lemma msq_pos : forall t, 0 < msq t.
Proof. intros t. unfold msq. pose proof (dot_nonneg d (phi t)). lra. Qed.

Lemma msq_neq0 : forall t, msq t <> 0.
Proof. intros t. pose proof (msq_pos t). lra. Qed.

(** ** 4.10–4.15 and 4.24–4.28  The N first-level regression models

    (4.24) Sigma_{i,f} : zhat_{i,f} = thetahat_{i,f}^T phi, i = 1..N.
    Indices here run 0..N-1.  [N >= 2n+1] is the design rule of the
    dissertation; it is never needed for any of the identities below, so it is
    recorded as a hypothesis but left unused. *)

Variable N : nat.
(* AMENDED: the dissertation writes N >= 2n+1 (pp. 23, 28, 60, 64, 72, 83).
   That inequality gives *existence* of the convex representation but not
   *uniqueness*: with N unknowns and d+1 equations the solution family has
   dimension N-(d+1).  Since the second level identifies alpha*_f, that target
   must be a single point, so the rule is tightened to equality.  With d = 2n
   this reads N = 2n+1.  See NOTE_convex_uniqueness.md and, for the
   uniqueness that equality buys, SLA_AppendixA.design_rule_exact. *)
Hypothesis H_N_exact : N = S d.                  (* N = 2n+1 with d = 2n *)

Variable th : nat -> R -> nat -> R.    (* thetahat_{i,f}(t) *)

Definition zh  (i : nat) (t : R) : R := dot d (th i t) (phi t).      (* (4.10)/(4.24) *)
Definition e   (i : nat) (t : R) : R := zh i t - z t.                (* (4.11)/(4.25) *)
Definition tht (i : nat) (t : R) (j : nat) : R := th i t j - thstar j. (* (4.14)/(4.26) *)
Definition eps (i : nat) (t : R) : R := e i t / msq t.               (* (4.13)/(4.27) *)

(** (4.15)/(4.28): the identification error is the linear form in the
    parametric error. *)
Theorem e_eq_dot_tht : forall i t, e i t = dot d (tht i t) (phi t).
Proof.
  intros i t. unfold e, zh, tht. rewrite H_param. rewrite dot_minus_l. reflexivity.
Qed.

Theorem eps_eq_dot_tht : forall i t, eps i t = dot d (tht i t) (phi t) / msq t.
Proof. intros i t. unfold eps. rewrite e_eq_dot_tht. reflexivity. Qed.

Lemma e_eq_eps_msq : forall i t, e i t = eps i t * msq t.
Proof. intros i t. unfold eps. field. apply msq_neq0. Qed.

(** ** 4.16–4.21  The normalized gradient law

    (4.16) J(thetahat) = eps^2 m^2 / 2, (4.17) thetahatdot = -Gamma grad J,
    (4.18) grad J = eps phi, hence (4.19) thetahatdot_{i,f} = -Gamma eps_{i,f} phi.
    Gamma = Gamma^T > 0 is diagonal with entries gam j > 0. *)

Variable gam : nat -> R.
Hypothesis H_gam : forall j, (j < d)%nat -> 0 < gam j.

Lemma gam_neq0 : forall j, (j < d)%nat -> gam j <> 0.
Proof. intros j Hj. pose proof (H_gam j Hj). lra. Qed.

(** (4.19)/(4.29) *)
Hypothesis H_law : forall i j, (i < N)%nat -> (j < d)%nat ->
  Deriv (fun t => th i t j) (fun t => - (gam j * eps i t * phi t j)).

(** (4.20)/(4.21): theta*_p is constant, so the parametric error moves exactly
    like the estimate. *)
Theorem tht_law : forall i j, (i < N)%nat -> (j < d)%nat ->
  Deriv (fun t => tht i t j) (fun t => - (gam j * eps i t * phi t j)).
Proof.
  intros i j Hi Hj. unfold tht.
  apply (D_ext (fun t => th i t j - thstar j)
               (fun t => - (gam j * eps i t * phi t j) - 0)).
  - intros; reflexivity.
  - intros; ring.
  - apply D_minus; [apply H_law; assumption | apply D_const].
Qed.

(** ** Generic machinery: quadratic Lyapunov forms

    Every Lyapunov function of the chapter has the shape
    Wq n c T = (1/2) sum_j T_j^2 / c_j, i.e. (4.22) and (4.57)/(4.68). *)

Definition Wq (n : nat) (c : nat -> R) (T : R -> nat -> R) (t : R) : R :=
  / 2 * Sum n (fun j => / c j * (T t j * T t j)).

Lemma Wq_deriv : forall n (c : nat -> R) (T T' : R -> nat -> R),
  (forall j, (j < n)%nat -> Deriv (fun t => T t j) (fun t => T' t j)) ->
  Deriv (Wq n c T) (fun t => Sum n (fun j => / c j * (T t j * T' t j))).
Proof.
  intros n c T T' HT.
  apply (D_ext
           (fun t => / 2 * Sum n (fun j => / c j * (T t j * T t j)))
           (fun t => / 2 * Sum n (fun j =>
              / c j * (T' t j * T t j + T t j * T' t j)))).
  - intros; reflexivity.
  - intros t.
    rewrite (Sum_ext n
               (fun j => / c j * (T' t j * T t j + T t j * T' t j))
               (fun j => 2 * (/ c j * (T t j * T' t j))))
      by (intros; ring).
    rewrite Sum_scal_l. field.
  - unfold Wq. apply D_scal. apply D_Sum. intros j Hj.
    apply D_scal. apply D_mult; apply HT; assumption.
Qed.

Lemma Wq_nonneg : forall n c T t,
  (forall j, (j < n)%nat -> 0 < c j) -> 0 <= Wq n c T t.
Proof.
  intros n c T t Hc. unfold Wq.
  assert (0 <= Sum n (fun j => / c j * (T t j * T t j))).
  { apply Sum_nonneg. intros j Hj.
    apply Rmult_le_pos.
    - left. apply Rinv_0_lt_compat. apply Hc; assumption.
    - apply Rle_0_sqr. }
  lra.
Qed.

Lemma Wq_init0 : forall n c T,
  (forall j, (j < n)%nat -> T 0 j = 0) -> Wq n c T 0 = 0.
Proof.
  intros n c T H. unfold Wq.
  rewrite (Sum_zero n (fun j => / c j * (T 0 j * T 0 j)))
    by (intros j Hj; rewrite H by assumption; ring).
  ring.
Qed.

(** If a quadratic form starts at zero and its derivative is never positive,
    the underlying vector is identically zero for all t >= 0.  This is the
    rigorous replacement for the ODE-uniqueness argument used implicitly in
    the dissertation (and in Narendra et al., "point 3"). *)
Lemma quad_zero : forall n (c : nat -> R) (T : R -> nat -> R) (W' : R -> R),
  (forall j, (j < n)%nat -> 0 < c j) ->
  Deriv (Wq n c T) W' ->
  (forall t, W' t <= 0) ->
  (forall j, (j < n)%nat -> T 0 j = 0) ->
  forall t, 0 <= t -> forall j, (j < n)%nat -> T t j = 0.
Proof.
  intros n c T W' Hc HD Hneg Hinit t Ht j Hj.
  assert (Hle : Wq n c T t <= Wq n c T 0)
    by (apply (nonincr_of_nonpos_deriv _ W' HD Hneg); assumption).
  rewrite (Wq_init0 n c T Hinit) in Hle.
  assert (Hge : 0 <= Wq n c T t) by (apply Wq_nonneg; assumption).
  assert (Hz : Sum n (fun k => / c k * (T t k * T t k)) = 0)
    by (unfold Wq in Hle, Hge; lra).
  assert (Hterm : / c j * (T t j * T t j) = 0).
  { apply (Sum_eq0_all n (fun k => / c k * (T t k * T t k))); try assumption.
    intros k Hk. apply Rmult_le_pos.
    - left. apply Rinv_0_lt_compat. apply Hc; assumption.
    - apply Rle_0_sqr. }
  assert (Hci : / c j <> 0).
  { apply Rgt_not_eq. apply Rinv_0_lt_compat. apply Hc; assumption. }
  destruct (Rmult_integral _ _ Hterm) as [H1|H1]; [contradiction|].
  destruct (Rmult_integral _ _ H1) as [H2|H2]; assumption.
Qed.

(** Specialisation to the gradient law: this is the computation behind
    (4.23), (4.30) and (4.44). *)
Lemma grad_Wq_deriv : forall (T : R -> nat -> R) (E : R -> R),
  (forall j, (j < d)%nat -> Deriv (fun t => T t j) (fun t => - (gam j * E t * phi t j))) ->
  Deriv (Wq d gam T) (fun t => - (E t * dot d (T t) (phi t))).
Proof.
  intros T E HT.
  apply (D_ext (Wq d gam T)
               (fun t => Sum d (fun j => / gam j * (T t j * - (gam j * E t * phi t j))))).
  - intros; reflexivity.
  - intros t. unfold dot.
    rewrite (Sum_ext d
               (fun j => / gam j * (T t j * - (gam j * E t * phi t j)))
               (fun j => - E t * (T t j * phi t j)))
      by (intros j Hj; field; apply gam_neq0; assumption).
    rewrite Sum_scal_l. ring.
  - apply Wq_deriv. assumption.
Qed.

(** ** 4.22–4.23  Stability of the first-level estimator

    V(thetatilde_{i,f}) = thetatilde^T Gamma^{-1} thetatilde / 2  and
    Vdot = -eps_{i,f}^2 m^2 <= 0. *)

Definition V1 (i : nat) : R -> R := Wq d gam (tht i).      (* (4.22) *)

Theorem V1_dyn : forall i, (i < N)%nat ->
  Deriv (V1 i) (fun t => - (eps i t * eps i t * msq t)).   (* (4.23) *)
Proof.
  intros i Hi. unfold V1.
  apply (D_ext (Wq d gam (tht i)) (fun t => - (eps i t * dot d (tht i t) (phi t)))).
  - intros; reflexivity.
  - intros t. rewrite <- e_eq_dot_tht. rewrite (e_eq_eps_msq i t). ring.
  - apply grad_Wq_deriv. intros j Hj. apply tht_law; assumption.
Qed.

Corollary V1_nonincreasing : forall i, (i < N)%nat ->
  forall a b, a <= b -> V1 i b <= V1 i a.
Proof.
  intros i Hi.
  apply (nonincr_of_nonpos_deriv _ _ (V1_dyn i Hi)).
  intros t. pose proof (msq_pos t) as Hm.
  pose proof (Rle_0_sqr (eps i t)) as Hsq. unfold Rsqr in Hsq. nra.
Qed.

(** ** 4.30  Dynamics of the identification errors *)

Definition phiGphi (t : R) : R := Sum d (fun j => gam j * (phi t j * phi t j)).

Lemma gen_e_dyn : forall (T : R -> nat -> R) (E : R -> R),
  (forall j, (j < d)%nat -> Deriv (fun t => T t j) (fun t => - (gam j * E t * phi t j))) ->
  Deriv (fun t => dot d (T t) (phi t))
        (fun t => - (E t * phiGphi t) + dot d (T t) (phid t)).
Proof.
  intros T E HT.
  apply (D_ext
           (fun t => Sum d (fun j => T t j * phi t j))
           (fun t => Sum d (fun j => - (gam j * E t * phi t j) * phi t j
                                     + T t j * phid t j))).
  - intros; reflexivity.
  - intros t. unfold phiGphi, dot.
    rewrite Sum_plus.
    rewrite (Sum_ext d
               (fun j => - (gam j * E t * phi t j) * phi t j)
               (fun j => - E t * (gam j * (phi t j * phi t j))))
      by (intros; ring).
    rewrite Sum_scal_l. ring.
  - apply D_Sum. intros j Hj. apply D_mult; [apply HT; assumption | apply H_phi; assumption].
Qed.

(** (4.30):  edot_{i,f} = -(1/m^2) e_{i,f} phi^T Gamma phi + thetatilde^T phidot. *)
Theorem e_dyn : forall i, (i < N)%nat ->
  Deriv (e i) (fun t => - (eps i t * phiGphi t) + dot d (tht i t) (phid t)).
Proof.
  intros i Hi.
  apply (D_ext (fun t => dot d (tht i t) (phi t))
               (fun t => - (eps i t * phiGphi t) + dot d (tht i t) (phid t))).
  - intros t. symmetry. apply e_eq_dot_tht.
  - intros; reflexivity.
  - apply gen_e_dyn. intros j Hj. apply tht_law; assumption.
Qed.

(** ** 4.31–4.40  Convex combinations and the virtual model *)

Variable beta : nat -> R.
Hypothesis H_beta_sum : Sum N beta = 1.                          (* (4.31) *)
Hypothesis H_beta_rng : forall i, (i < N)%nat -> 0 <= beta i <= 1. (* (4.31) *)

Definition thv  (t : R) (j : nat) : R := Sum N (fun i => th i t j * beta i). (* (4.31) *)
Definition zhv  (t : R) : R := dot d (thv t) (phi t).                        (* (4.32) *)
Definition ev   (t : R) : R := zhv t - z t.                                  (* (4.33) *)
Definition thtv (t : R) (j : nat) : R := thv t j - thstar j.                 (* (4.34) *)
Definition epsv (t : R) : R := ev t / msq t.

(** General fact: a linear combination of the estimates produces the same
    linear combination of the model outputs.  Used for (4.32) and (4.42). *)
Lemma dot_lincomb : forall (c : nat -> R) (t : R),
  dot d (fun j => Sum N (fun i => th i t j * c i)) (phi t)
  = Sum N (fun i => zh i t * c i).
Proof.
  intros c t. unfold dot, zh, dot.
  rewrite (Sum_ext d
             (fun j => Sum N (fun i => th i t j * c i) * phi t j)
             (fun j => Sum N (fun i => th i t j * c i * phi t j)))
    by (intros; rewrite Sum_scal_r; reflexivity).
  rewrite Sum_swap.
  apply Sum_ext. intros i Hi.
  rewrite <- Sum_scal_r. apply Sum_ext. intros j Hj. ring.
Qed.

(** (4.35): the parametric error of the virtual model is the *same* convex
    combination of the parametric errors of the first-level models. *)
Theorem thtv_convex : forall t j, thtv t j = Sum N (fun i => tht i t j * beta i).
Proof.
  intros t j. unfold thtv, thv, tht.
  rewrite (Sum_ext N
             (fun i => (th i t j - thstar j) * beta i)
             (fun i => th i t j * beta i - thstar j * beta i))
    by (intros; ring).
  rewrite Sum_minus, Sum_scal_l, H_beta_sum. ring.
Qed.

(** The identification error of the virtual model is *identically* the convex
    combination of the first-level identification errors.  The dissertation
    argues (between 4.37 and 4.40) that the two only converge exponentially and
    coincide when e_v(0) = sum beta_i e_i(0); in fact, with regression models,
    they are equal by construction — no initial condition is needed. *)
Theorem ev_convex : forall t, ev t = Sum N (fun i => e i t * beta i).
Proof.
  intros t. unfold ev, zhv, thv, e.
  rewrite dot_lincomb.
  rewrite (Sum_ext N (fun i => (zh i t - z t) * beta i)
                     (fun i => zh i t * beta i - z t * beta i))
    by (intros; ring).
  rewrite Sum_minus, Sum_scal_l, H_beta_sum. ring.
Qed.

Theorem epsv_convex : forall t, epsv t = Sum N (fun i => eps i t * beta i).
Proof.
  intros t. unfold epsv, eps.
  rewrite (Sum_ext N (fun i => e i t / msq t * beta i)
                     (fun i => / msq t * (e i t * beta i)))
    by (intros; unfold Rdiv; ring).
  rewrite Sum_scal_l, <- ev_convex. unfold Rdiv. ring.
Qed.

Theorem ev_eq_dot_thtv : forall t, ev t = dot d (thtv t) (phi t).
Proof.
  intros t. unfold ev, zhv, thtv. rewrite H_param. rewrite dot_minus_l. reflexivity.
Qed.

(** (4.36)/(4.40): the virtual model obeys an adaptive law of exactly the same
    form as the first-level models. *)
Theorem thv_law : forall j, (j < d)%nat ->
  Deriv (fun t => thv t j) (fun t => - (gam j * epsv t * phi t j)).
Proof.
  intros j Hj. unfold thv.
  apply (D_ext
           (fun t => Sum N (fun i => th i t j * beta i))
           (fun t => Sum N (fun i => - (gam j * eps i t * phi t j) * beta i + th i t j * 0))).
  - intros; reflexivity.
  - intros t.
    rewrite (Sum_ext N
               (fun i => - (gam j * eps i t * phi t j) * beta i + th i t j * 0)
               (fun i => - (gam j * phi t j) * (eps i t * beta i)))
      by (intros; ring).
    rewrite Sum_scal_l, <- epsv_convex. ring.
  - apply D_Sum. intros i Hi.
    apply D_mult; [apply H_law; assumption | apply D_const].
Qed.

Theorem thtv_law : forall j, (j < d)%nat ->
  Deriv (fun t => thtv t j) (fun t => - (gam j * epsv t * phi t j)).
Proof.
  intros j Hj. unfold thtv.
  apply (D_ext (fun t => thv t j - thstar j)
               (fun t => - (gam j * epsv t * phi t j) - 0)).
  - intros; reflexivity.
  - intros; ring.
  - apply D_minus; [apply thv_law; assumption | apply D_const].
Qed.

(** (4.37) = (4.39): the convex combination of the first-level error dynamics
    and the virtual-model error dynamics are the same function. *)
Theorem ev_dyn : Deriv ev (fun t => - (epsv t * phiGphi t) + dot d (thtv t) (phid t)).
Proof.
  apply (D_ext (fun t => dot d (thtv t) (phi t))
               (fun t => - (epsv t * phiGphi t) + dot d (thtv t) (phid t))).
  - intros t. symmetry. apply ev_eq_dot_thtv.
  - intros; reflexivity.
  - apply gen_e_dyn. intros j Hj. apply thtv_law; assumption.
Qed.

(** ** 4.41–4.45  The alpha* parametrization and invariance of the convex hull *)

Variable astar : nat -> R.
Hypothesis H_astar_sum : Sum N astar = 1.                          (* (4.41) *)
Hypothesis H_astar_rng : forall i, (i < N)%nat -> 0 <= astar i <= 1. (* (4.41) *)

(** (4.41) is *assumed only at the initial instant*: theta*_p lies in the
    convex hull of the initial estimates. *)
Hypothesis H_astar_init : forall j, (j < d)%nat ->
  Sum N (fun i => th i 0 j * astar i) = thstar j.

Definition tha (t : R) (j : nat) : R := Sum N (fun i => tht i t j * astar i).
Definition ea  (t : R) : R := Sum N (fun i => e i t * astar i).   (* (4.43)/(4.45) *)

Lemma tha_init0 : forall j, (j < d)%nat -> tha 0 j = 0.
Proof.
  intros j Hj. unfold tha, tht.
  rewrite (Sum_ext N (fun i => (th i 0 j - thstar j) * astar i)
                     (fun i => th i 0 j * astar i - thstar j * astar i))
    by (intros; ring).
  rewrite Sum_minus, Sum_scal_l, H_astar_sum, H_astar_init by assumption. ring.
Qed.

Lemma ea_eq_dot_tha : forall t, ea t = dot d (tha t) (phi t).
Proof.
  intros t. unfold ea, tha, dot.
  rewrite (Sum_ext N (fun i => e i t * astar i)
                     (fun i => dot d (tht i t) (phi t) * astar i))
    by (intros i Hi; rewrite e_eq_dot_tht; reflexivity).
  unfold dot.
  rewrite (Sum_ext N (fun i => Sum d (fun j => tht i t j * phi t j) * astar i)
                     (fun i => Sum d (fun j => tht i t j * astar i * phi t j)))
    by (intros i Hi; rewrite <- Sum_scal_r; apply Sum_ext; intros; ring).
  rewrite Sum_swap.
  apply Sum_ext. intros j Hj. rewrite <- Sum_scal_r. reflexivity.
Qed.

Lemma tha_law : forall j, (j < d)%nat ->
  Deriv (fun t => tha t j) (fun t => - (gam j * (ea t / msq t) * phi t j)).
Proof.
  intros j Hj. unfold tha.
  apply (D_ext
           (fun t => Sum N (fun i => tht i t j * astar i))
           (fun t => Sum N (fun i => - (gam j * eps i t * phi t j) * astar i + tht i t j * 0))).
  - intros; reflexivity.
  - intros t.
    rewrite (Sum_ext N
               (fun i => - (gam j * eps i t * phi t j) * astar i + tht i t j * 0)
               (fun i => - (gam j * phi t j) * (/ msq t * (e i t * astar i))))
      by (intros; unfold eps, Rdiv; ring).
    rewrite Sum_scal_l, Sum_scal_l. unfold ea, Rdiv. ring.
  - apply D_Sum. intros i Hi.
    apply D_mult; [apply tht_law; assumption | apply D_const].
Qed.

(** *** Invariance of the convex hull (the key claim behind 4.41 and 4.45)

    If theta*_p is in the convex hull of the initial estimates, it stays in the
    convex hull of the estimates *with the same coefficients* for all t >= 0.
    This is item 3) of Narendra–Wang–Chen; the dissertation states it as
    "os parâmetros verdadeiros pertencem ao fecho convexo" without proof. *)

Theorem hull_invariance : forall t, 0 <= t -> forall j, (j < d)%nat -> tha t j = 0.
Proof.
  apply (quad_zero d gam tha (fun t => - (ea t / msq t * ea t))).
  - exact H_gam.
  - apply (D_ext (Wq d gam tha) (fun t => - (ea t / msq t * dot d (tha t) (phi t)))).
    + intros; reflexivity.
    + intros t. rewrite <- ea_eq_dot_tha. reflexivity.
    + apply grad_Wq_deriv. apply tha_law.
  - intros t. pose proof (msq_pos t) as Hm.
    assert (Hinv : 0 <= / msq t) by (left; apply Rinv_0_lt_compat; assumption).
    pose proof (Rle_0_sqr (ea t)) as Hsq. unfold Rsqr in Hsq.
    unfold Rdiv. nra.
  - exact tha_init0.
Qed.

(** (4.41) now holds at every instant, not just at t = 0. *)
Corollary theta_star_in_hull : forall t, 0 <= t -> forall j, (j < d)%nat ->
  Sum N (fun i => th i t j * astar i) = thstar j.
Proof.
  intros t Ht j Hj.
  pose proof (hull_invariance t Ht j Hj) as H. unfold tha, tht in H.
  rewrite (Sum_ext N (fun i => (th i t j - thstar j) * astar i)
                     (fun i => th i t j * astar i - thstar j * astar i)) in H
    by (intros; ring).
  rewrite Sum_minus, Sum_scal_l, H_astar_sum in H. lra.
Qed.

(** (4.45): the convex combination of the identification errors with the
    coefficients alpha* is identically zero (for t >= 0), which is the exact
    version of the dissertation's "tends to 0 exponentially". *)
Corollary ea_zero : forall t, 0 <= t -> ea t = 0.
Proof.
  intros t Ht. rewrite ea_eq_dot_tha. unfold dot.
  apply Sum_zero. intros j Hj. rewrite (hull_invariance t Ht j Hj). ring.
Qed.

(** (4.44): the dynamics of e_alpha.  In general there is the extra term
    tha^T phidot; under hull invariance it vanishes and (4.44) is recovered. *)
Theorem ea_dyn_general :
  Deriv ea (fun t => - (ea t / msq t * phiGphi t) + dot d (tha t) (phid t)).
Proof.
  apply (D_ext (fun t => dot d (tha t) (phi t))
               (fun t => - (ea t / msq t * phiGphi t) + dot d (tha t) (phid t))).
  - intros t. symmetry. apply ea_eq_dot_tha.
  - intros; reflexivity.
  - apply gen_e_dyn. apply tha_law.
Qed.

Theorem ea_dyn : (forall t j, (j < d)%nat -> tha t j = 0) ->
  Deriv ea (fun t => - (ea t / msq t * phiGphi t)).
Proof.
  intros Hz.
  apply (D_ext ea (fun t => - (ea t / msq t * phiGphi t) + dot d (tha t) (phid t))).
  - intros; reflexivity.
  - intros t.
    replace (dot d (tha t) (phid t)) with 0.
    + ring.
    + unfold dot. symmetry. apply Sum_zero. intros j Hj. rewrite Hz by assumption. ring.
  - apply ea_dyn_general.
Qed.

(** ** 4.46–4.51  Elimination of alpha_N

    With 0-based indices the last model is number [M] and N = M+1.
    (4.50): E_f = [eps_1 - eps_N, ..., eps_{N-1} - eps_N]. *)

Variable M : nat.
Hypothesis H_NM : N = S M.

Definition Ev (t : R) (i : nat) : R := eps i t - eps M t.       (* (4.50) *)

Lemma sum_eps_astar : forall t, Sum N (fun i => eps i t * astar i) = ea t / msq t.
Proof.
  intros t. unfold eps, ea.
  rewrite (Sum_ext N (fun i => e i t / msq t * astar i)
                     (fun i => / msq t * (e i t * astar i)))
    by (intros; unfold Rdiv; ring).
  rewrite Sum_scal_l. unfold Rdiv. ring.
Qed.

(** (4.49)/(4.51), in the exact form: the residual on the right-hand side is
    e_alpha/m^2, which is zero as soon as theta*_p is in the hull. *)
Theorem E_alpha_star : forall t,
  Sum M (fun i => Ev t i * astar i) = - eps M t + ea t / msq t.
Proof.
  intros t.
  assert (HS : Sum N (fun i => eps i t * astar i)
               = Sum M (fun i => eps i t * astar i) + eps M t * astar M)
    by (rewrite H_NM; reflexivity).
  assert (HA : Sum N astar = Sum M astar + astar M) by (rewrite H_NM; reflexivity).
  rewrite H_astar_sum in HA.
  rewrite sum_eps_astar in HS.
  unfold Ev.
  rewrite (Sum_ext M (fun i => (eps i t - eps M t) * astar i)
                     (fun i => eps i t * astar i - eps M t * astar i))
    by (intros; ring).
  rewrite Sum_minus, Sum_scal_l, HS.
  assert (HaM : astar M = 1 - Sum M astar) by lra.
  rewrite HaM. ring.
Qed.

(** (4.51) proper. *)
Corollary E_alpha_star_exact : forall t, 0 <= t ->
  Sum M (fun i => Ev t i * astar i) = - eps M t.
Proof.
  intros t Ht. rewrite E_alpha_star, (ea_zero t Ht). unfold Rdiv. ring.
Qed.

(** ** 4.52–4.58  Conventional second level adaptation *)

Variable gn : R.                                (* gamma_{n2,f} of (4.52) *)
Hypothesis H_gn : 0 < gn.

Section SLA_conventional.

Variable alp : R -> nat -> R.                   (* alpha_f(t) in R^M *)

Definition alpt (t : R) (i : nat) : R := alp t i - astar i.              (* (4.54) *)
Definition Ealp  (t : R) : R := Sum M (fun i => Ev t i * alp t i).       (* E_f alpha_f *)
Definition Ealpt (t : R) : R := Sum M (fun i => Ev t i * alpt t i).      (* E_f alphatilde_f *)

(** (4.52): alphadot_f = -gamma E_f^T E_f alpha_f - gamma E_f^T eps_{N,f}.
    Since E_f is a row vector, (E_f^T E_f alpha_f)_i = E_i (E_f alpha_f). *)
Hypothesis H_sla : forall i, (i < M)%nat ->
  Deriv (fun t => alp t i)
        (fun t => - gn * (Ev t i * Ealp t) - gn * (Ev t i * eps M t)).

Lemma Ealp_split : forall t, Ealp t = Ealpt t + (- eps M t + ea t / msq t).
Proof.
  intros t. unfold Ealp, Ealpt, alpt.
  rewrite <- E_alpha_star.
  rewrite (Sum_ext M (fun i => Ev t i * (alp t i - astar i))
                     (fun i => Ev t i * alp t i - Ev t i * astar i))
    by (intros; ring).
  rewrite Sum_minus. ring.
Qed.

(** (4.55) + (4.56): the parametric-error dynamics of the second level. *)
Theorem alpt_dyn : forall i, (i < M)%nat ->
  Deriv (fun t => alpt t i)
        (fun t => - gn * (Ev t i * Ealpt t) - gn * (Ev t i * (ea t / msq t))).
Proof.
  intros i Hi. unfold alpt.
  apply (D_ext (fun t => alp t i - astar i)
               (fun t => (- gn * (Ev t i * Ealp t) - gn * (Ev t i * eps M t)) - 0)).
  - intros; reflexivity.
  - intros t. rewrite Ealp_split. ring.
  - apply D_minus; [apply H_sla; assumption | apply D_const].
Qed.

(** *** 4.57–4.58  Lyapunov analysis

    The dissertation's candidate (4.57) is built on the *extended* vector
    alphabar_f whose last entry is 1 - vec1 alpha_f, so
    alphabartilde = [alphatilde ; -vec1 alphatilde].  We treat both that
    function [Vb] and the reduced one [Vr] used by Narendra et al. *)

Definition Vr : R -> R := Wq M (fun _ => 1) alpt.   (* (1/2) alphatilde^T alphatilde *)

(** Reduced Lyapunov function: this is the correct counterpart of (4.58),
    matching eq. (24) of Narendra–Wang–Chen. *)
Theorem Vr_dyn :
  Deriv Vr (fun t => - gn * (Ealpt t * Ealpt t) - gn * (Ealpt t * (ea t / msq t))).
Proof.
  unfold Vr.
  apply (D_ext (Wq M (fun _ => 1) alpt)
               (fun t => Sum M (fun i => / 1 * (alpt t i *
                  (- gn * (Ev t i * Ealpt t) - gn * (Ev t i * (ea t / msq t)))))));
    [ intros; reflexivity | | apply Wq_deriv; apply alpt_dyn ].
  intros t. set (r := ea t / msq t).
  rewrite (Sum_ext M
             (fun i => / 1 * (alpt t i *
                (- gn * (Ev t i * Ealpt t) - gn * (Ev t i * r))))
             (fun i => (- gn * Ealpt t - gn * r) * (Ev t i * alpt t i)))
    by (intros; rewrite Rinv_1; ring).
  rewrite Sum_scal_l.
  replace (Sum M (fun i => Ev t i * alpt t i)) with (Ealpt t) by reflexivity.
  ring.
Qed.

Corollary Vr_nonincreasing : (forall t, ea t = 0) ->
  forall a b, a <= b -> Vr b <= Vr a.
Proof.
  intros Hea.
  apply (nonincr_of_nonpos_deriv _ _ Vr_dyn).
  intros t. rewrite (Hea t).
  replace (0 / msq t) with 0 by (unfold Rdiv; ring).
  pose proof (Rle_0_sqr (Ealpt t)) as Hsq. unfold Rsqr in Hsq. nra.
Qed.

(** The dissertation's own candidate (4.57). *)
Definition Sb (t : R) : R := Sum M (alpt t).      (* vec1 . alphatilde_f *)
Definition SE (t : R) : R := Sum M (Ev t).        (* vec1 . E_f          *)

Definition Vb (t : R) : R :=
  / (2 * gn) * (Sum M (fun i => alpt t i * alpt t i) + Sb t * Sb t).   (* (4.57) *)

Lemma Sb_dyn :
  Deriv Sb (fun t => - gn * (SE t * Ealpt t) - gn * (SE t * (ea t / msq t))).
Proof.
  apply (D_ext (fun t => Sum M (fun i => alpt t i))
               (fun t => Sum M (fun i => - gn * (Ev t i * Ealpt t)
                                         - gn * (Ev t i * (ea t / msq t))))).
  - intros; reflexivity.
  - intros t. set (r := ea t / msq t).
    rewrite (Sum_ext M
               (fun i => - gn * (Ev t i * Ealpt t) - gn * (Ev t i * r))
               (fun i => (- gn * Ealpt t - gn * r) * Ev t i))
      by (intros; ring).
    rewrite Sum_scal_l. unfold SE. ring.
  - apply D_Sum. apply alpt_dyn.
Qed.

(** The *exact* derivative of the dissertation's Lyapunov candidate (4.57).
    Compare with (4.58), which claims
       Vdot = -N alphatilde^T E^T E alphatilde - N alphatilde^T E^T e_alpha/m^2.
    The extra cross term  Sb * SE  is what (4.58) replaces by the factor N. *)
Theorem Vb_dyn :
  Deriv Vb (fun t => - ((Ealpt t + Sb t * SE t) * (Ealpt t + ea t / msq t))).
Proof.
  unfold Vb.
  apply (D_ext
           (fun t => / (2 * gn) * (Sum M (fun i => alpt t i * alpt t i) + Sb t * Sb t))
           (fun t => / (2 * gn) *
              (Sum M (fun i => (- gn * (Ev t i * Ealpt t)
                                - gn * (Ev t i * (ea t / msq t))) * alpt t i
                               + alpt t i * (- gn * (Ev t i * Ealpt t)
                                             - gn * (Ev t i * (ea t / msq t))))
               + ((- gn * (SE t * Ealpt t) - gn * (SE t * (ea t / msq t))) * Sb t
                  + Sb t * (- gn * (SE t * Ealpt t) - gn * (SE t * (ea t / msq t))))))).
  - intros; reflexivity.
  - intros t. set (r := ea t / msq t).
    rewrite (Sum_ext M
               (fun i => (- gn * (Ev t i * Ealpt t)
                          - gn * (Ev t i * r)) * alpt t i
                         + alpt t i * (- gn * (Ev t i * Ealpt t)
                                       - gn * (Ev t i * r)))
               (fun i => (- 2 * gn * (Ealpt t + r)) * (Ev t i * alpt t i)))
      by (intros; ring).
    rewrite Sum_scal_l.
    replace (Sum M (fun i => Ev t i * alpt t i)) with (Ealpt t) by reflexivity.
    assert (Hgn : gn <> 0) by lra.
    field. exact Hgn.
  - apply D_scal. apply D_plus.
    + apply D_Sum. intros i Hi. apply D_mult; apply alpt_dyn; assumption.
    + apply D_mult; apply Sb_dyn.
Qed.

(** *** The factor N of (4.58) does not follow

    With e_alpha = 0 the exact derivative is  -gn (Ealphatilde + Sb SE) Ealphatilde
    while (4.58) asserts  -gn N (Ealphatilde)^2.  These disagree, and the exact
    one is not even sign definite. *)

Corollary Vb_deriv_differs_from_4_58 : forall t,
  (M = 2)%nat -> ea t = 0 -> Ealpt t = 1 -> Sb t = 1 -> SE t = 1 ->
  - ((Ealpt t + Sb t * SE t) * (Ealpt t + ea t / msq t))
  <> - (INR (S M) * (Ealpt t * Ealpt t)).
Proof.
  intros t HM He HE HS HSE.
  rewrite HE, HS, HSE, He, HM.
  replace (0 / msq t) with 0 by (unfold Rdiv; ring).
  simpl. lra.
Qed.

Corollary Vb_deriv_can_be_positive : forall t,
  ea t = 0 -> Ealpt t = 1 -> Sb t = -2 -> SE t = 1 ->
  0 < - ((Ealpt t + Sb t * SE t) * (Ealpt t + ea t / msq t)).
Proof.
  intros t He HE HS HSE.
  rewrite HE, HS, HSE, He.
  replace (0 / msq t) with 0 by (unfold Rdiv; ring).
  lra.
Qed.

End SLA_conventional.

(** ** 4.60–4.69  Second level adaptation with a forgetting factor (SLAFF) *)

Section SLA_forgetting.

Variable sig : R.                              (* the forgetting factor sigma *)
Hypothesis H_sig : 0 < sig.

Variable Mf : R -> nat -> nat -> R.            (* M_f of (4.65) *)
Variable vf : R -> nat -> R.                   (* v_f of (4.65) *)

Hypothesis H_Mf0 : forall i j, Mf 0 i j = 0.   (* M_f(0) = 0 *)
Hypothesis H_vf0 : forall i, vf 0 i = 0.       (* v_f(0) = 0 *)

(** (4.66): the differential equations generating M_f and v_f. *)
Hypothesis H_Mf : forall i j, (i < M)%nat -> (j < M)%nat ->
  Deriv (fun t => Mf t i j) (fun t => - sig * Mf t i j + Ev t i * Ev t j).
Hypothesis H_vf : forall i, (i < M)%nat ->
  Deriv (fun t => vf t i) (fun t => - sig * vf t i + Ev t i * eps M t).

(** (4.65) <-> (4.66): the integrating-factor identity.  Saying
    M_f(t) = int_0^t e^{-sigma (t-tau)} E_f^T E_f dtau  with M_f(0) = 0 is
    exactly saying that e^{sigma t} M_f(t) has derivative e^{sigma t} E^T E. *)
Theorem Mf_integrating_factor : forall i j, (i < M)%nat -> (j < M)%nat ->
  Deriv (fun t => exp (sig * t) * Mf t i j)
        (fun t => exp (sig * t) * (Ev t i * Ev t j)).
Proof.
  intros i j Hi Hj.
  apply (D_ext (fun t => exp (sig * t) * Mf t i j)
               (fun t => sig * exp (sig * t) * Mf t i j
                         + exp (sig * t) * (- sig * Mf t i j + Ev t i * Ev t j))).
  - intros; reflexivity.
  - intros; ring.
  - apply D_mult; [apply D_exp_lin | apply H_Mf; assumption].
Qed.

Theorem vf_integrating_factor : forall i, (i < M)%nat ->
  Deriv (fun t => exp (sig * t) * vf t i)
        (fun t => exp (sig * t) * (Ev t i * eps M t)).
Proof.
  intros i Hi.
  apply (D_ext (fun t => exp (sig * t) * vf t i)
               (fun t => sig * exp (sig * t) * vf t i
                         + exp (sig * t) * (- sig * vf t i + Ev t i * eps M t))).
  - intros; reflexivity.
  - intros; ring.
  - apply D_mult; [apply D_exp_lin | apply H_vf; assumption].
Qed.

(** M_f is positive semi-definite for all t >= 0.  This is what makes the
    quadratic term of (4.69) sign definite; the dissertation asserts it
    implicitly by writing M_f as a convolution integral of E^T E. *)
Definition MQ (x : nat -> R) (t : R) : R :=
  Sum M (fun i => x i * Sum M (fun j => Mf t i j * x j)).
Definition EX (x : nat -> R) (t : R) : R := Sum M (fun i => Ev t i * x i).

Lemma MQ_dyn : forall x, Deriv (MQ x) (fun t => - sig * MQ x t + EX x t * EX x t).
Proof.
  intros x.
  apply (D_ext
           (fun t => Sum M (fun i => x i * Sum M (fun j => Mf t i j * x j)))
           (fun t => Sum M (fun i => 0 * Sum M (fun j => Mf t i j * x j)
              + x i * Sum M (fun j => (- sig * Mf t i j + Ev t i * Ev t j) * x j
                                      + Mf t i j * 0)))).
  - intros; reflexivity.
  - intros t.
    rewrite (Sum_ext M
      (fun i => 0 * Sum M (fun j => Mf t i j * x j)
         + x i * Sum M (fun j => (- sig * Mf t i j + Ev t i * Ev t j) * x j
                                 + Mf t i j * 0))
      (fun i => (- sig) * (x i * Sum M (fun j => Mf t i j * x j))
                + (Sum M (fun j => Ev t j * x j)) * (Ev t i * x i))).
    + rewrite Sum_comb. unfold MQ, EX. ring.
    + intros i Hi.
      rewrite (Sum_ext M
        (fun j => (- sig * Mf t i j + Ev t i * Ev t j) * x j + Mf t i j * 0)
        (fun j => (- sig) * (Mf t i j * x j) + (Ev t i) * (Ev t j * x j)))
        by (intros; ring).
      rewrite Sum_comb. ring.
  - apply D_Sum. intros i Hi.
    apply D_mult; [apply D_const|].
    apply D_Sum. intros j Hj.
    apply D_mult; [apply H_Mf; assumption | apply D_const].
Qed.

Theorem Mf_psd : forall (x : nat -> R) t, 0 <= t -> 0 <= MQ x t.
Proof.
  intros x t Ht.
  assert (Hexp : Deriv (fun t => exp (sig * t) * MQ x t)
                       (fun t => exp (sig * t) * (EX x t * EX x t))).
  { apply (D_ext (fun t => exp (sig * t) * MQ x t)
                 (fun t => sig * exp (sig * t) * MQ x t
                           + exp (sig * t) * (- sig * MQ x t + EX x t * EX x t))).
    - intros; reflexivity.
    - intros; ring.
    - apply D_mult; [apply D_exp_lin | apply MQ_dyn]. }
  assert (Hq0 : MQ x 0 = 0).
  { unfold MQ. apply Sum_zero. intros i Hi.
    rewrite (Sum_zero M (fun j => Mf 0 i j * x j))
      by (intros j Hj; rewrite H_Mf0; ring). ring. }
  assert (Hmono : exp (sig * 0) * MQ x 0 <= exp (sig * t) * MQ x t).
  { apply (nondecr_of_nonneg_deriv _ _ Hexp); [| assumption].
    intros t0. apply Rmult_le_pos; [left; apply exp_pos | apply Rle_0_sqr]. }
  rewrite Hq0 in Hmono.
  assert (Hpos : 0 < exp (sig * t)) by apply exp_pos.
  nra.
Qed.

(** *** The SLAFF adaptive law (4.67) *)

Variable alpF : R -> nat -> R.

Definition alpFt (t : R) (i : nat) : R := alpF t i - astar i.
Definition EalpF  (t : R) : R := Sum M (fun i => Ev t i * alpF t i).
Definition EalpFt (t : R) : R := Sum M (fun i => Ev t i * alpFt t i).

(** the residual driven by e_alpha:  M_f alpha*_f + v_f *)
Definition qres (t : R) (i : nat) : R :=
  Sum M (fun j => Mf t i j * astar j) + vf t i.

(** (4.67): alphadot_f = gamma (-M_f alpha_f - E^T E alpha_f - v_f - E^T eps_N). *)
Hypothesis H_slaff : forall i, (i < M)%nat ->
  Deriv (fun t => alpF t i)
        (fun t => gn * (- Sum M (fun j => Mf t i j * alpF t j)
                        - Ev t i * EalpF t - vf t i - Ev t i * eps M t)).

Lemma EalpF_split : forall t, EalpF t = EalpFt t + (- eps M t + ea t / msq t).
Proof.
  intros t. unfold EalpF, EalpFt, alpFt.
  rewrite <- E_alpha_star.
  rewrite (Sum_ext M (fun i => Ev t i * (alpF t i - astar i))
                     (fun i => Ev t i * alpF t i - Ev t i * astar i))
    by (intros; ring).
  rewrite Sum_minus. ring.
Qed.

Lemma Mf_alpF_split : forall t i,
  Sum M (fun j => Mf t i j * alpF t j)
  = Sum M (fun j => Mf t i j * alpFt t j) + Sum M (fun j => Mf t i j * astar j).
Proof.
  intros t i. unfold alpFt.
  rewrite <- Sum_plus. apply Sum_ext. intros; ring.
Qed.

(** The SLAFF parametric-error dynamics — the correct counterpart of the step
    between (4.67) and (4.69). *)
Theorem alpFt_dyn : forall i, (i < M)%nat ->
  Deriv (fun t => alpFt t i)
        (fun t => gn * (- Sum M (fun j => Mf t i j * alpFt t j)
                        - Ev t i * EalpFt t
                        - Ev t i * (ea t / msq t)
                        - qres t i)).
Proof.
  intros i Hi.
  apply (D_ext (fun t => alpF t i - astar i)
               (fun t => gn * (- Sum M (fun j => Mf t i j * alpF t j)
                               - Ev t i * EalpF t - vf t i - Ev t i * eps M t) - 0)).
  - intros; reflexivity.
  - intros t. rewrite EalpF_split, Mf_alpF_split. unfold qres. ring.
  - apply D_minus; [apply H_slaff; assumption | apply D_const].
Qed.

(** When theta*_p is in the convex hull (so e_alpha = 0), the residual vanishes
    identically, and the dissertation's extra term of (4.69) disappears. *)
Lemma qres_dyn : forall i, (i < M)%nat ->
  Deriv (fun t => qres t i) (fun t => - sig * qres t i + Ev t i * (ea t / msq t)).
Proof.
  intros i Hi. unfold qres.
  apply (D_ext
           (fun t => Sum M (fun j => Mf t i j * astar j) + vf t i)
           (fun t => Sum M (fun j => (- sig * Mf t i j + Ev t i * Ev t j) * astar j
                                     + Mf t i j * 0)
                     + (- sig * vf t i + Ev t i * eps M t))).
  - intros; reflexivity.
  - intros t.
    rewrite (Sum_ext M
      (fun j => (- sig * Mf t i j + Ev t i * Ev t j) * astar j + Mf t i j * 0)
      (fun j => (- sig) * (Mf t i j * astar j) + (Ev t i) * (Ev t j * astar j)))
      by (intros; ring).
    rewrite Sum_comb, E_alpha_star. unfold qres. ring.
  - apply D_plus.
    + apply D_Sum. intros j Hj. apply D_mult; [apply H_Mf; assumption | apply D_const].
    + apply H_vf; assumption.
Qed.

Theorem qres_zero : (forall t, ea t = 0) ->
  forall t, 0 <= t -> forall i, (i < M)%nat -> qres t i = 0.
Proof.
  intros Hea.
  apply (quad_zero M (fun _ => 1) qres (fun t => - sig * Sum M (fun i => qres t i * qres t i))).
  - intros; lra.
  - apply (D_ext (Wq M (fun _ => 1) qres)
                 (fun t => Sum M (fun i => / 1 * (qres t i *
                    (- sig * qres t i + Ev t i * (ea t / msq t)))))).
    + intros; reflexivity.
    + intros t. rewrite (Hea t).
      rewrite (Sum_ext M
        (fun i => / 1 * (qres t i * (- sig * qres t i + Ev t i * (0 / msq t))))
        (fun i => - sig * (qres t i * qres t i)))
        by (intros; rewrite Rinv_1; unfold Rdiv; ring).
      rewrite Sum_scal_l. reflexivity.
    + apply Wq_deriv. apply qres_dyn.
  - intros t.
    assert (0 <= Sum M (fun i => qres t i * qres t i))
      by (apply Sum_nonneg; intros; apply Rle_0_sqr). nra.
  - intros i Hi. unfold qres.
    rewrite (Sum_zero M (fun j => Mf 0 i j * astar j))
      by (intros j Hj; rewrite H_Mf0; ring).
    rewrite H_vf0. ring.
Qed.

(** *** 4.68–4.69  Lyapunov analysis of SLAFF

    (4.68) is the same candidate as (4.57).  Below is the exact derivative for
    the *reduced* function; as for (4.58), the factor N of (4.69) does not
    follow, and (4.69) also omits v_f from its last term (it writes
    -N alphatilde^T M_f alpha*_f where the correct residual is
    M_f alpha*_f + v_f). *)

Definition VrF : R -> R := Wq M (fun _ => 1) alpFt.        (* (4.68) *)

Theorem VrF_dyn :
  Deriv VrF (fun t => gn * (- Sum M (fun i => alpFt t i * Sum M (fun j => Mf t i j * alpFt t j))
                            - EalpFt t * EalpFt t
                            - EalpFt t * (ea t / msq t)
                            - Sum M (fun i => alpFt t i * qres t i))).
Proof.
  unfold VrF.
  apply (D_ext (Wq M (fun _ => 1) alpFt)
               (fun t => Sum M (fun i => / 1 * (alpFt t i *
                  (gn * (- Sum M (fun j => Mf t i j * alpFt t j)
                         - Ev t i * EalpFt t
                         - Ev t i * (ea t / msq t)
                         - qres t i))))));
    [ intros; reflexivity | | apply Wq_deriv; apply alpFt_dyn ].
  intros t. set (r := ea t / msq t).
  rewrite (Sum_ext M
    (fun i => / 1 * (alpFt t i *
       (gn * (- Sum M (fun j => Mf t i j * alpFt t j)
              - Ev t i * EalpFt t - Ev t i * r - qres t i))))
    (fun i => (- gn) * (alpFt t i * Sum M (fun j => Mf t i j * alpFt t j))
              + (- gn) * (alpFt t i * qres t i)
              + (gn * (- EalpFt t - r)) * (Ev t i * alpFt t i)))
    by (intros; rewrite Rinv_1; ring).
  rewrite Sum_comb3.
  replace (Sum M (fun i => Ev t i * alpFt t i)) with (EalpFt t) by reflexivity.
  ring.
Qed.

(** With e_alpha = 0 the derivative is negative semi-definite: the quadratic
    form in M_f is PSD and the residual vanishes.  This is the content that
    (4.69) intends. *)
Theorem VrF_nonpos : (forall t, ea t = 0) ->
  forall t, 0 <= t ->
    gn * (- Sum M (fun i => alpFt t i * Sum M (fun j => Mf t i j * alpFt t j))
          - EalpFt t * EalpFt t
          - EalpFt t * (ea t / msq t)
          - Sum M (fun i => alpFt t i * qres t i)) <= 0.
Proof.
  intros Hea t Ht.
  rewrite (Hea t).
  rewrite (Sum_zero M (fun i => alpFt t i * qres t i))
    by (intros i Hi; rewrite (qres_zero Hea t Ht i Hi); ring).
  replace (0 / msq t) with 0 by (unfold Rdiv; ring).
  pose proof (Mf_psd (alpFt t) t Ht) as Hpsd. unfold MQ in Hpsd.
  pose proof (Rle_0_sqr (EalpFt t)) as Hsq. unfold Rsqr in Hsq.
  nra.
Qed.

End SLA_forgetting.

End Chapter4.
