function estrutura = make_struct_MQ                         ...
        (t_inicial,t_final,h, Aw, Ap, bp, ordem,P0,Plinha,  ...
         cond_inicial_p,cond_inicial_est_p, teta_inicial,   ...
         Beta,PMax,minp)

estrutura = convert_names_to_fields ...
        (t_inicial,t_final,h, Aw, Ap, bp, ordem,P0,Plinha,  ...
         cond_inicial_p,cond_inicial_est_p, teta_inicial,   ...
         Beta,PMax,minp);

end