function estrutura = make_struct_Grad                                    ...
        (t_inicial,t_final,h, Aw, Ap, bp, ordem, P, gama,cond_inicial_p, ...
         cond_inicial_est_p, teta_inicial,beta,refA,refF)

estrutura = convert_names_to_fields ...
        (t_inicial,t_final,h, Aw, Ap, bp, ordem, P, gama,cond_inicial_p, ...
         cond_inicial_est_p, teta_inicial,beta,refA,refF);

end