(*  Title:      SLA_Chapter4.thy
    Author:     Isabelle/HOL port of the Coq development in ../coq

    Chapter 4 (equations 4.1-4.69) of

      Pedro Yochinori Gushiken, "Adaptacao de Segundo Nivel como Tecnica de
      Estimacao de Parametros e sua Aplicacao ao Controle Adaptativo por
      Modelo de Referencia", MSc dissertation, UFRN, 2018 -- Chapter 4,
      "Estimacao de Parametros, Ordem n".

    Background sources consulted for the underlying framework:
      - Z. Han & K. S. Narendra, IEEE TAC 57(1):78-89, 2012.
      - K. S. Narendra, Y. Wang, W. Chen, "The Rationale for Second Level
        Adaptation", arXiv:1510.04989.
      - P. Ioannou & J. Sun, "Robust Adaptive Control", 1996.
      - G. Chowdhary et al., IJACSP 27(4):280-301, 2013.

    Equations 4.1-4.7 and 4.9 only fix NOTATION for the filters that generate
    the regressor phi.  Their entire mathematical content downstream is that
    phi is differentiable and that z = thstar^T phi, which is the assumption
    H_param (4.8) of the locale "plant".

    STRUCTURE.  Where the Coq development used one long section with
    accumulating Variables, this port uses a chain of locales.  Each locale
    adds exactly the parameters and hypotheses of the corresponding block of
    the chapter, so every theorem is stated under the weakest hypotheses that
    support it, and SLA_Instance discharges the whole hypothesis set by
    "interpretation" rather than by threading a dozen explicit arguments
    through every statement.

    TWO DISCREPANCIES ARE PROVED, not assumed.  See Vb_dyn,
    Vb_deriv_differs_from_4_58, Vb_deriv_can_be_positive,
    Vb_deriv_positive_witness, and the comment above VrF_dyn.

    AMENDMENT.  The design rule is assumed here as N = d + 1 EXACTLY, not
    N >= d + 1 as written in the dissertation.  See ../NOTE_convex_uniqueness.md
    and SLA_AppendixA: the inequality gives existence of alpha*, the equality
    gives uniqueness, and the second level needs alpha*_f to be a point
    because it is the parameter it identifies.
*)

theory SLA_Chapter4
  imports SLA_Prelim
begin

section \<open>4.1-4.9: plant and linear parametrization\<close>

text \<open>The plant (4.1)-(4.2) is @{text "G_p(s) = N_p(s)/D_p(s)"} of order n and
  relative degree one.  Filtering by a monic Hurwitz @{text "Lambda(s)"} of
  degree n (4.4) and collecting the filtered signals (4.5) produces the
  regressor @{text phi} generated by (4.6)-(4.7), and the signal
  @{text "z = s^n/Lambda(s) y"} (4.9).  @{text d} is the dimension 2n of
  @{text thstar}.\<close>

locale plant =
  fixes d :: nat
    and phi :: "real \<Rightarrow> nat \<Rightarrow> real"     \<comment> \<open>the regressor phi(t)\<close>
    and phid :: "real \<Rightarrow> nat \<Rightarrow> real"    \<comment> \<open>its time derivative\<close>
    and thstar :: "nat \<Rightarrow> real"          \<comment> \<open>theta*_p, the true parameters\<close>
    and z :: "real \<Rightarrow> real"              \<comment> \<open>the filtered output z(t)\<close>
  assumes H_phi: "\<And>j. j < d \<Longrightarrow> Deriv (\<lambda>t. phi t j) (\<lambda>t. phid t j)"
      and H_param: "\<And>t. z t = dot d thstar (phi t)"        \<comment> \<open>(4.8)\<close>
begin

text \<open>(4.12): @{text "n_s^2 = phi^T phi"} is the normalizing signal and
  @{text "m^2 = 1 + n_s^2"}.\<close>

definition msq :: "real \<Rightarrow> real"
  where "msq t = 1 + dot d (phi t) (phi t)"

lemma msq_pos: "0 < msq t"
  using dot_nonneg[of d "phi t"] by (simp add: msq_def)

lemma msq_neq0: "msq t \<noteq> 0"
  using msq_pos[of t] by simp

end

section \<open>4.10-4.15 and 4.24-4.30: the N first-level regression models\<close>

text \<open>Indices run @{text "0 .. N-1"}.\<close>

locale first_level_sig = plant +
  fixes N :: nat
    and th :: "nat \<Rightarrow> real \<Rightarrow> nat \<Rightarrow> real"   \<comment> \<open>thetahat_i(t)\<close>
    and gam :: "nat \<Rightarrow> real"                 \<comment> \<open>the diagonal of Gamma\<close>
begin

definition zh :: "nat \<Rightarrow> real \<Rightarrow> real"                \<comment> \<open>(4.10)/(4.24)\<close>
  where "zh i t = dot d (th i t) (phi t)"

definition e :: "nat \<Rightarrow> real \<Rightarrow> real"                 \<comment> \<open>(4.11)/(4.25)\<close>
  where "e i t = zh i t - z t"

definition tht :: "nat \<Rightarrow> real \<Rightarrow> nat \<Rightarrow> real"        \<comment> \<open>(4.14)/(4.26)\<close>
  where "tht i t j = th i t j - thstar j"

definition eps :: "nat \<Rightarrow> real \<Rightarrow> real"               \<comment> \<open>(4.13)/(4.27)\<close>
  where "eps i t = e i t / msq t"

text \<open>(4.15)/(4.28): the identification error is the linear form in the
  parametric error.  This needs no hypothesis on the adaptive law.\<close>

theorem e_eq_dot_tht: "e i t = dot d (tht i t) (phi t)"
  unfolding e_def zh_def tht_def by (simp add: dot_diff_left H_param)

theorem eps_eq_dot_tht: "eps i t = dot d (tht i t) (phi t) / msq t"
  by (simp add: eps_def e_eq_dot_tht)

lemma e_eq_eps_msq: "e i t = eps i t * msq t"
  using msq_neq0[of t] by (simp add: eps_def)

end

text \<open>(4.16) @{text "J = eps^2 m^2 / 2"}, (4.17)
  @{text "thetahatdot = -Gamma grad J"}, (4.18) @{text "grad J = eps phi"},
  hence the normalized gradient law (4.19)/(4.29).

  The design rule is @{text H_N_exact} below.  The dissertation writes
  @{text "N >= 2n+1"}; this port assumes @{text "N = 2n+1 = d+1"} exactly --
  see ../NOTE_convex_uniqueness.md.  Like the Coq original's @{text H_N_min},
  it is recorded but never used by any identity of this chapter: what the
  chapter consumes is only the EXISTENCE of alpha* (assumption
  @{text H_astar_init} below).  Its role is to make alpha* unique, hence a
  well-defined identification target for the second level; that is proved in
  SLA_AppendixA.\<close>

locale first_level = first_level_sig +
  assumes H_N_exact: "N = Suc d"                     \<comment> \<open>N = 2n+1, d = 2n\<close>
      and H_gam: "\<And>j. j < d \<Longrightarrow> 0 < gam j"
      and H_law: "\<And>i j. i < N \<Longrightarrow> j < d \<Longrightarrow>
                    Deriv (\<lambda>t. th i t j) (\<lambda>t. - (gam j * eps i t * phi t j))"
begin

lemma gam_neq0: "j < d \<Longrightarrow> gam j \<noteq> 0"
  using H_gam[of j] by simp

text \<open>(4.20)/(4.21): theta*_p is constant, so the parametric error moves
  exactly like the estimate.\<close>

theorem tht_law:
  assumes "i < N" and "j < d"
  shows "Deriv (\<lambda>t. tht i t j) (\<lambda>t. - (gam j * eps i t * phi t j))"
proof (rule Deriv_cong)
  show "Deriv (\<lambda>t. th i t j - thstar j)
              (\<lambda>t. - (gam j * eps i t * phi t j) - 0)"
    by (rule Deriv_diff[OF H_law[OF assms] Deriv_const])
qed (auto simp: tht_def)

subsection \<open>Generic machinery for the gradient law\<close>

text \<open>The computation behind (4.23), (4.30) and (4.44).\<close>

lemma grad_Wq_deriv:
  assumes HT: "\<And>j. j < d \<Longrightarrow>
                 Deriv (\<lambda>t. T t j) (\<lambda>t. - (gam j * E t * phi t j))"
  shows "Deriv (Wq d gam T) (\<lambda>t. - (E t * dot d (T t) (phi t)))"
proof (rule Deriv_cong_deriv[OF Wq_deriv[OF HT]])
  fix t
  have "(\<Sum>j<d. inverse (gam j) * (T t j * - (gam j * E t * phi t j)))
        = (\<Sum>j<d. - E t * (T t j * phi t j))"
  proof (rule sum.cong[OF refl])
    fix j assume "j \<in> {..<d}"
    hence "gam j \<noteq> 0" by (simp add: gam_neq0)
    thus "inverse (gam j) * (T t j * - (gam j * E t * phi t j))
          = - E t * (T t j * phi t j)"
      by (simp add: field_simps)
  qed
  also have "\<dots> = - E t * (\<Sum>j<d. T t j * phi t j)"
    by (simp add: sum_distrib_left)
  finally show "(\<Sum>j<d. inverse (gam j) * (T t j * - (gam j * E t * phi t j)))
                = - (E t * dot d (T t) (phi t))"
    by (simp add: dot_def)
qed

subsection \<open>4.22-4.23: stability of the first-level estimator\<close>

definition V1 :: "nat \<Rightarrow> real \<Rightarrow> real"     \<comment> \<open>(4.22)\<close>
  where "V1 i = Wq d gam (tht i)"

theorem V1_dyn:                            \<comment> \<open>(4.23)\<close>
  assumes "i < N"
  shows "Deriv (V1 i) (\<lambda>t. - (eps i t * eps i t * msq t))"
  unfolding V1_def
proof (rule Deriv_cong_deriv[OF grad_Wq_deriv[OF tht_law[OF assms]]])
  fix t
  show "- (eps i t * dot d (tht i t) (phi t)) = - (eps i t * eps i t * msq t)"
    using e_eq_dot_tht[of i t] e_eq_eps_msq[of i t] by simp
qed

corollary V1_nonincreasing:
  assumes "i < N" and "a \<le> b"
  shows "V1 i b \<le> V1 i a"
proof (rule nonincr_of_nonpos_deriv[OF V1_dyn[OF assms(1)] _ assms(2)])
  fix s :: real
  have "0 \<le> eps i s * eps i s" by (rule zero_le_square)
  moreover have "0 \<le> msq s" using msq_pos[of s] by simp
  ultimately have "0 \<le> eps i s * eps i s * msq s" by (rule mult_nonneg_nonneg)
  thus "- (eps i s * eps i s * msq s) \<le> 0" by simp
qed

subsection \<open>4.30: dynamics of the identification errors\<close>

definition phiGphi :: "real \<Rightarrow> real"
  where "phiGphi t = (\<Sum>j<d. gam j * (phi t j * phi t j))"

lemma gen_e_dyn:
  assumes HT: "\<And>j. j < d \<Longrightarrow>
                 Deriv (\<lambda>t. T t j) (\<lambda>t. - (gam j * E t * phi t j))"
  shows "Deriv (\<lambda>t. dot d (T t) (phi t))
               (\<lambda>t. - (E t * phiGphi t) + dot d (T t) (phid t))"
proof (rule Deriv_cong)
  have D: "Deriv (\<lambda>t. T t j * phi t j)
                 (\<lambda>t. - (gam j * E t * phi t j) * phi t j + T t j * phid t j)"
    if "j < d" for j
    by (rule Deriv_mult[OF HT[OF that] H_phi[OF that]])
  show "Deriv (\<lambda>t. \<Sum>j<d. T t j * phi t j)
              (\<lambda>t. \<Sum>j<d. - (gam j * E t * phi t j) * phi t j
                          + T t j * phid t j)"
    by (rule Deriv_sum[OF D])
next
  fix t show "(\<Sum>j<d. T t j * phi t j) = dot d (T t) (phi t)"
    by (simp add: dot_def)
next
  fix t
  have "(\<Sum>j<d. - (gam j * E t * phi t j) * phi t j + T t j * phid t j)
        = (\<Sum>j<d. - E t * (gam j * (phi t j * phi t j)) + T t j * phid t j)"
    by (rule sum.cong) (auto simp: algebra_simps)
  also have "\<dots> = (\<Sum>j<d. - E t * (gam j * (phi t j * phi t j)))
                  + (\<Sum>j<d. T t j * phid t j)"
    by (rule sum.distrib)
  also have "\<dots> = - E t * (\<Sum>j<d. gam j * (phi t j * phi t j))
                  + (\<Sum>j<d. T t j * phid t j)"
    by (simp add: sum_distrib_left)
  finally show "(\<Sum>j<d. - (gam j * E t * phi t j) * phi t j
                          + T t j * phid t j)
        = - (E t * phiGphi t) + dot d (T t) (phid t)"
    by (simp add: phiGphi_def dot_def)
qed

text \<open>(4.30): @{text "edot_i = -(1/m^2) e_i phi^T Gamma phi
  + thetatilde^T phidot"}.\<close>

theorem e_dyn:
  assumes "i < N"
  shows "Deriv (e i) (\<lambda>t. - (eps i t * phiGphi t) + dot d (tht i t) (phid t))"
  by (rule Deriv_cong[OF gen_e_dyn[OF tht_law[OF assms]]])
     (simp_all add: e_eq_dot_tht)

end

section \<open>4.31-4.40: convex combinations and the virtual model\<close>

locale virtual_model = first_level +
  fixes beta :: "nat \<Rightarrow> real"
  assumes H_beta_sum: "(\<Sum>i<N. beta i) = 1"                    \<comment> \<open>(4.31)\<close>
      and H_beta_rng: "\<And>i. i < N \<Longrightarrow> 0 \<le> beta i \<and> beta i \<le> 1" \<comment> \<open>(4.31)\<close>
begin

definition thv :: "real \<Rightarrow> nat \<Rightarrow> real"      \<comment> \<open>(4.31)\<close>
  where "thv t j = (\<Sum>i<N. th i t j * beta i)"

definition zhv :: "real \<Rightarrow> real"             \<comment> \<open>(4.32)\<close>
  where "zhv t = dot d (thv t) (phi t)"

definition ev :: "real \<Rightarrow> real"              \<comment> \<open>(4.33)\<close>
  where "ev t = zhv t - z t"

definition thtv :: "real \<Rightarrow> nat \<Rightarrow> real"     \<comment> \<open>(4.34)\<close>
  where "thtv t j = thv t j - thstar j"

definition epsv :: "real \<Rightarrow> real"
  where "epsv t = ev t / msq t"

text \<open>A linear combination of the estimates produces the same linear
  combination of the model outputs.  Used for (4.32) and (4.42).\<close>

lemma dot_lincomb:
  "(\<Sum>j<d. (\<Sum>i<N. th i t j * c i) * phi t j) = (\<Sum>i<N. zh i t * c i)"
proof -
  have "(\<Sum>j<d. (\<Sum>i<N. th i t j * c i) * phi t j)
        = (\<Sum>j<d. \<Sum>i<N. th i t j * c i * phi t j)"
    by (simp add: sum_distrib_right)
  also have "\<dots> = (\<Sum>i<N. \<Sum>j<d. th i t j * c i * phi t j)"
    by (rule sum.swap)
  also have "\<dots> = (\<Sum>i<N. zh i t * c i)"
  proof (rule sum.cong[OF refl])
    fix i assume "i \<in> {..<N}"
    have "(\<Sum>j<d. th i t j * c i * phi t j)
          = (\<Sum>j<d. (th i t j * phi t j) * c i)"
      by (rule sum.cong) (auto simp: algebra_simps)
    also have "\<dots> = (\<Sum>j<d. th i t j * phi t j) * c i"
      by (simp add: sum_distrib_right)
    finally show "(\<Sum>j<d. th i t j * c i * phi t j) = zh i t * c i"
      by (simp add: zh_def dot_def)
  qed
  finally show ?thesis .
qed

text \<open>(4.35): the parametric error of the virtual model is the SAME convex
  combination of the parametric errors of the first-level models.\<close>

theorem thtv_convex: "thtv t j = (\<Sum>i<N. tht i t j * beta i)"
proof -
  have "(\<Sum>i<N. tht i t j * beta i)
        = (\<Sum>i<N. th i t j * beta i) - (\<Sum>i<N. thstar j * beta i)"
    by (simp add: tht_def sum_subtractf algebra_simps)
  also have "(\<Sum>i<N. thstar j * beta i) = thstar j"
    by (simp add: sum_distrib_left[symmetric] H_beta_sum)
  finally show ?thesis by (simp add: thtv_def thv_def)
qed

text \<open>The identification error of the virtual model is IDENTICALLY the convex
  combination of the first-level identification errors.  The dissertation
  argues (between 4.37 and 4.40) that the two only converge exponentially and
  coincide when @{text "e_v(0) = sum beta_i e_i(0)"}; in fact, with linear
  regression models, they are equal by construction -- no condition on the
  initial values is needed.\<close>

theorem ev_convex: "ev t = (\<Sum>i<N. e i t * beta i)"
proof -
  have "(\<Sum>i<N. e i t * beta i)
        = (\<Sum>i<N. zh i t * beta i) - (\<Sum>i<N. z t * beta i)"
    by (simp add: e_def sum_subtractf algebra_simps)
  also have "(\<Sum>i<N. z t * beta i) = z t"
    by (simp add: sum_distrib_left[symmetric] H_beta_sum)
  finally show ?thesis
    by (simp add: ev_def zhv_def dot_def thv_def dot_lincomb)
qed

theorem epsv_convex: "epsv t = (\<Sum>i<N. eps i t * beta i)"
proof -
  have "(\<Sum>i<N. eps i t * beta i) = (\<Sum>i<N. (e i t * beta i) / msq t)"
    by (rule sum.cong) (auto simp: eps_def)
  also have "\<dots> = (\<Sum>i<N. e i t * beta i) / msq t"
    by (simp add: sum_divide_distrib)
  finally show ?thesis by (simp add: epsv_def ev_convex)
qed

theorem ev_eq_dot_thtv: "ev t = dot d (thtv t) (phi t)"
  unfolding ev_def zhv_def thtv_def by (simp add: dot_diff_left H_param)

text \<open>(4.36)/(4.40): the virtual model obeys an adaptive law of exactly the
  same form as the first-level models.\<close>

theorem thv_law:
  assumes j: "j < d"
  shows "Deriv (\<lambda>t. thv t j) (\<lambda>t. - (gam j * epsv t * phi t j))"
proof (rule Deriv_cong)
  have D: "Deriv (\<lambda>t. th i t j * beta i)
                 (\<lambda>t. - (gam j * eps i t * phi t j) * beta i + th i t j * 0)"
    if "i < N" for i
    by (rule Deriv_mult[OF H_law[OF that j] Deriv_const])
  show "Deriv (\<lambda>t. \<Sum>i<N. th i t j * beta i)
              (\<lambda>t. \<Sum>i<N. - (gam j * eps i t * phi t j) * beta i
                          + th i t j * 0)"
    by (rule Deriv_sum[OF D])
next
  fix t show "(\<Sum>i<N. th i t j * beta i) = thv t j" by (simp add: thv_def)
next
  fix t
  have "(\<Sum>i<N. - (gam j * eps i t * phi t j) * beta i + th i t j * 0)
        = (\<Sum>i<N. - (gam j * phi t j) * (eps i t * beta i))"
    by (rule sum.cong) (auto simp: algebra_simps)
  also have "\<dots> = - (gam j * phi t j) * (\<Sum>i<N. eps i t * beta i)"
    by (simp add: sum_distrib_left)
  finally show "(\<Sum>i<N. - (gam j * eps i t * phi t j) * beta i
                        + th i t j * 0)
                = - (gam j * epsv t * phi t j)"
    by (simp add: epsv_convex algebra_simps)
qed

theorem thtv_law:
  assumes "j < d"
  shows "Deriv (\<lambda>t. thtv t j) (\<lambda>t. - (gam j * epsv t * phi t j))"
proof (rule Deriv_cong)
  show "Deriv (\<lambda>t. thv t j - thstar j)
              (\<lambda>t. - (gam j * epsv t * phi t j) - 0)"
    by (rule Deriv_diff[OF thv_law[OF assms] Deriv_const])
qed (auto simp: thtv_def)

text \<open>(4.37) = (4.39): the convex combination of the first-level error
  dynamics and the virtual-model error dynamics are the same function.\<close>

theorem ev_dyn:
  "Deriv ev (\<lambda>t. - (epsv t * phiGphi t) + dot d (thtv t) (phid t))"
proof (rule Deriv_cong[OF gen_e_dyn])
  show "\<And>j. j < d \<Longrightarrow>
          Deriv (\<lambda>t. thtv t j) (\<lambda>t. - (gam j * epsv t * phi t j))"
    by (rule thtv_law)
qed (simp_all add: ev_eq_dot_thtv)

end

section \<open>4.41-4.45: the alpha* parametrization and invariance of the convex hull\<close>

text \<open>(4.41) is assumed only at the initial instant: theta*_p lies in the
  convex hull of the INITIAL estimates.  By the amendment (see
  ../NOTE_convex_uniqueness.md) the design rule @{text H_N_exact} makes this
  alpha* unique, so it is a well-defined identification target; existence is
  all the theorems below consume.\<close>

locale hull_models = first_level +
  fixes astar :: "nat \<Rightarrow> real"
  assumes H_astar_sum: "(\<Sum>i<N. astar i) = 1"                      \<comment> \<open>(4.41)\<close>
      and H_astar_rng: "\<And>i. i < N \<Longrightarrow> 0 \<le> astar i \<and> astar i \<le> 1" \<comment> \<open>(4.41)\<close>
      and H_astar_init: "\<And>j. j < d \<Longrightarrow>
                           (\<Sum>i<N. th i 0 j * astar i) = thstar j"
begin

definition tha :: "real \<Rightarrow> nat \<Rightarrow> real"
  where "tha t j = (\<Sum>i<N. tht i t j * astar i)"

definition ea :: "real \<Rightarrow> real"              \<comment> \<open>(4.43)/(4.45)\<close>
  where "ea t = (\<Sum>i<N. e i t * astar i)"

lemma tha_init0:
  assumes j: "j < d"
  shows "tha 0 j = 0"
proof -
  have "tha 0 j = (\<Sum>i<N. th i 0 j * astar i) - (\<Sum>i<N. thstar j * astar i)"
    by (simp add: tha_def tht_def sum_subtractf algebra_simps)
  also have "(\<Sum>i<N. thstar j * astar i) = thstar j"
    by (simp add: sum_distrib_left[symmetric] H_astar_sum)
  finally show ?thesis by (simp add: H_astar_init[OF j])
qed

lemma ea_eq_dot_tha: "ea t = dot d (tha t) (phi t)"
proof -
  have "ea t = (\<Sum>i<N. \<Sum>j<d. (tht i t j * astar i) * phi t j)"
    unfolding ea_def
  proof (rule sum.cong[OF refl])
    fix i assume "i \<in> {..<N}"
    have "e i t * astar i = (\<Sum>j<d. tht i t j * phi t j) * astar i"
      by (simp add: e_eq_dot_tht dot_def)
    also have "\<dots> = (\<Sum>j<d. (tht i t j * phi t j) * astar i)"
      by (simp add: sum_distrib_right)
    also have "\<dots> = (\<Sum>j<d. (tht i t j * astar i) * phi t j)"
      by (rule sum.cong) (auto simp: algebra_simps)
    finally show "e i t * astar i
                  = (\<Sum>j<d. tht i t j * astar i * phi t j)" .
  qed
  also have "\<dots> = (\<Sum>j<d. \<Sum>i<N. (tht i t j * astar i) * phi t j)"
    by (rule sum.swap)
  also have "\<dots> = dot d (tha t) (phi t)"
    by (simp add: dot_def tha_def sum_distrib_right)
  finally show ?thesis .
qed

lemma tha_law:
  assumes j: "j < d"
  shows "Deriv (\<lambda>t. tha t j) (\<lambda>t. - (gam j * (ea t / msq t) * phi t j))"
proof (rule Deriv_cong)
  have D: "Deriv (\<lambda>t. tht i t j * astar i)
                 (\<lambda>t. - (gam j * eps i t * phi t j) * astar i
                      + tht i t j * 0)"
    if "i < N" for i
    by (rule Deriv_mult[OF tht_law[OF that j] Deriv_const])
  show "Deriv (\<lambda>t. \<Sum>i<N. tht i t j * astar i)
              (\<lambda>t. \<Sum>i<N. - (gam j * eps i t * phi t j) * astar i
                          + tht i t j * 0)"
    by (rule Deriv_sum[OF D])
next
  fix t show "(\<Sum>i<N. tht i t j * astar i) = tha t j" by (simp add: tha_def)
next
  fix t
  have "(\<Sum>i<N. - (gam j * eps i t * phi t j) * astar i + tht i t j * 0)
        = (\<Sum>i<N. (- (gam j * phi t j) * (e i t * astar i)) / msq t)"
    by (rule sum.cong) (auto simp: eps_def algebra_simps)
  also have "\<dots> = (\<Sum>i<N. - (gam j * phi t j) * (e i t * astar i)) / msq t"
    by (simp add: sum_divide_distrib)
  also have "\<dots> = - (gam j * phi t j) * (\<Sum>i<N. e i t * astar i) / msq t"
    by (simp add: sum_distrib_left)
  finally show "(\<Sum>i<N. - (gam j * eps i t * phi t j) * astar i
                        + tht i t j * 0)
                = - (gam j * (ea t / msq t) * phi t j)"
    by (simp add: ea_def algebra_simps)
qed

subsection \<open>Invariance of the convex hull\<close>

text \<open>If theta*_p is in the convex hull of the initial estimates, it stays in
  the convex hull of the estimates WITH THE SAME COEFFICIENTS for all
  @{term "0 \<le> t"}.  This is item 3) of Narendra-Wang-Chen; the dissertation
  states it as "os parametros verdadeiros pertencem ao fecho convexo" without
  proof.  Here it is a Lyapunov argument closed by the mean value theorem,
  replacing the implicit appeal to ODE uniqueness.\<close>

theorem hull_invariance:
  assumes t: "0 \<le> t" and j: "j < d"
  shows "tha t j = 0"
proof (rule quad_zero[where c = gam and T = tha
                        and W' = "\<lambda>t. - (ea t / msq t * ea t)"])
  show "\<And>j. j < d \<Longrightarrow> 0 < gam j" by (rule H_gam)
next
  show "Deriv (Wq d gam tha) (\<lambda>t. - (ea t / msq t * ea t))"
  proof (rule Deriv_cong_deriv[OF grad_Wq_deriv[OF tha_law]])
    fix s :: real
    show "- (ea s / msq s * dot d (tha s) (phi s)) = - (ea s / msq s * ea s)"
      using ea_eq_dot_tha[of s] by simp
  qed
next
  fix s :: real
  have "0 \<le> (ea s * ea s) / msq s"
    by (rule divide_nonneg_pos[OF zero_le_square msq_pos])
  moreover have "ea s / msq s * ea s = (ea s * ea s) / msq s" by simp
  ultimately show "- (ea s / msq s * ea s) \<le> 0" by simp
next
  show "\<And>j. j < d \<Longrightarrow> tha 0 j = 0" by (rule tha_init0)
next
  show "0 \<le> t" by (rule t)
next
  show "j < d" by (rule j)
qed

text \<open>(4.41) now holds at every instant, not just at @{term "t = 0"}.\<close>

corollary theta_star_in_hull:
  assumes t: "0 \<le> t" and j: "j < d"
  shows "(\<Sum>i<N. th i t j * astar i) = thstar j"
proof -
  have "tha t j = (\<Sum>i<N. th i t j * astar i) - (\<Sum>i<N. thstar j * astar i)"
    by (simp add: tha_def tht_def sum_subtractf algebra_simps)
  also have "(\<Sum>i<N. thstar j * astar i) = thstar j"
    by (simp add: sum_distrib_left[symmetric] H_astar_sum)
  finally show ?thesis using hull_invariance[OF t j] by simp
qed

text \<open>(4.45): the convex combination of the identification errors with the
  coefficients alpha* is IDENTICALLY zero for @{term "0 \<le> t"}, which is the
  exact version of the dissertation's "tends to 0 exponentially".  The
  dissertation's discussion of a nonzero @{text "e_alpha(0)"} applies to the
  practical case where the filter states are not initialised consistently -- a
  situation outside the model (4.8).\<close>

corollary ea_zero:
  assumes "0 \<le> t" shows "ea t = 0"
proof -
  have "\<And>j. j < d \<Longrightarrow> tha t j = 0" by (rule hull_invariance[OF assms])
  thus ?thesis by (simp add: ea_eq_dot_tha dot_zero_left)
qed

text \<open>(4.44): the dynamics of e_alpha.  In general there is the extra term
  @{text "tha^T phidot"}; under hull invariance it vanishes and (4.44) is
  recovered.\<close>

theorem ea_dyn_general:
  "Deriv ea (\<lambda>t. - (ea t / msq t * phiGphi t) + dot d (tha t) (phid t))"
  by (rule Deriv_cong[OF gen_e_dyn[OF tha_law]]) (simp_all add: ea_eq_dot_tha)

theorem ea_dyn:
  assumes Z: "\<And>t j. j < d \<Longrightarrow> tha t j = 0"
  shows "Deriv ea (\<lambda>t. - (ea t / msq t * phiGphi t))"
proof (rule Deriv_cong_deriv[OF ea_dyn_general])
  fix t show "- (ea t / msq t * phiGphi t) + dot d (tha t) (phid t)
              = - (ea t / msq t * phiGphi t)"
    by (simp add: dot_zero_left Z)
qed

end

section \<open>4.46-4.51: elimination of alpha_N\<close>

text \<open>With 0-based indices the last model is number @{text M} and
  @{text "N = M+1"}.  Under the amended design rule @{text H_N_exact} this
  means @{text "M = d"}.\<close>

locale second_level = hull_models +
  fixes M :: nat
    and gn :: real                     \<comment> \<open>gamma_{n2,f} of (4.52)\<close>
  assumes H_NM: "N = Suc M"
      and H_gn: "0 < gn"
begin

lemma M_eq_d: "M = d"
  using H_NM H_N_exact by simp

definition Ev :: "real \<Rightarrow> nat \<Rightarrow> real"       \<comment> \<open>(4.50)\<close>
  where "Ev t i = eps i t - eps M t"

lemma sum_eps_astar: "(\<Sum>i<N. eps i t * astar i) = ea t / msq t"
proof -
  have "(\<Sum>i<N. eps i t * astar i) = (\<Sum>i<N. (e i t * astar i) / msq t)"
    by (rule sum.cong) (auto simp: eps_def)
  also have "\<dots> = (\<Sum>i<N. e i t * astar i) / msq t"
    by (simp add: sum_divide_distrib)
  finally show ?thesis by (simp add: ea_def)
qed

text \<open>(4.49)/(4.51), in exact form: the residual on the right-hand side is
  @{text "e_alpha/m^2"}, which is zero as soon as theta*_p is in the hull.
  (4.48), @{text "astar M = 1 - sum_{i<M} astar i"}, is the step where
  @{thm sum.lessThan_Suc} peels the last summand -- exactly as in the Coq
  original, where the [Sum] fixpoint recursed on the last index.\<close>

theorem E_alpha_star:
  "(\<Sum>i<M. Ev t i * astar i) = - eps M t + ea t / msq t"
proof -
  have HS: "(\<Sum>i<N. eps i t * astar i)
            = (\<Sum>i<M. eps i t * astar i) + eps M t * astar M"
    by (simp add: H_NM)
  have HA: "(\<Sum>i<M. astar i) + astar M = 1"
    using H_astar_sum by (simp add: H_NM)
  have A: "(\<Sum>i<M. Ev t i * astar i)
           = (\<Sum>i<M. eps i t * astar i) - (\<Sum>i<M. eps M t * astar i)"
  proof -
    have "(\<Sum>i<M. Ev t i * astar i)
          = (\<Sum>i<M. eps i t * astar i - eps M t * astar i)"
      by (rule sum.cong) (auto simp: Ev_def algebra_simps)
    thus ?thesis by (simp add: sum_subtractf)
  qed
  have B: "(\<Sum>i<M. eps M t * astar i) = eps M t * (\<Sum>i<M. astar i)"
    by (simp add: sum_distrib_left)
  have C: "(\<Sum>i<M. eps i t * astar i) = ea t / msq t - eps M t * astar M"
    using HS by (simp add: sum_eps_astar)
  have "(\<Sum>i<M. Ev t i * astar i)
        = (ea t / msq t - eps M t * astar M) - eps M t * (\<Sum>i<M. astar i)"
    by (simp add: A B C)
  also have "\<dots> = ea t / msq t
                  - eps M t * ((\<Sum>i<M. astar i) + astar M)"
    by (simp add: algebra_simps)
  also have "\<dots> = - eps M t + ea t / msq t" by (simp add: HA)
  finally show ?thesis .
qed

text \<open>(4.51) proper.\<close>

corollary E_alpha_star_exact:
  "0 \<le> t \<Longrightarrow> (\<Sum>i<M. Ev t i * astar i) = - eps M t"
  by (simp add: E_alpha_star ea_zero)

end

section \<open>4.52-4.58: conventional second level adaptation\<close>

locale sla_sig = second_level +
  fixes alp :: "real \<Rightarrow> nat \<Rightarrow> real"     \<comment> \<open>alpha_f(t) in R^M\<close>
begin

definition alpt :: "real \<Rightarrow> nat \<Rightarrow> real"     \<comment> \<open>(4.53)/(4.54)\<close>
  where "alpt t i = alp t i - astar i"

definition Ealp :: "real \<Rightarrow> real"            \<comment> \<open>E_f alpha_f\<close>
  where "Ealp t = (\<Sum>i<M. Ev t i * alp t i)"

definition Ealpt :: "real \<Rightarrow> real"           \<comment> \<open>E_f alphatilde_f\<close>
  where "Ealpt t = (\<Sum>i<M. Ev t i * alpt t i)"

end

text \<open>(4.52): @{text "alphadot_f = -gamma E^T E alpha_f - gamma E^T eps_N"}.
  Since @{text E_f} is a row vector, @{text "(E^T E alpha)_i = E_i (E alpha)"}.\<close>

locale sla = sla_sig +
  assumes H_sla: "\<And>i. i < M \<Longrightarrow>
    Deriv (\<lambda>t. alp t i)
          (\<lambda>t. - gn * (Ev t i * Ealp t) - gn * (Ev t i * eps M t))"
begin

lemma Ealp_split: "Ealp t = Ealpt t + (- eps M t + ea t / msq t)"
proof -
  have "Ealpt t = (\<Sum>i<M. Ev t i * alp t i) - (\<Sum>i<M. Ev t i * astar i)"
    by (simp add: Ealpt_def alpt_def sum_subtractf algebra_simps)
  thus ?thesis by (simp add: Ealp_def E_alpha_star)
qed

text \<open>(4.55) + (4.56): the parametric-error dynamics of the second level.\<close>

theorem alpt_dyn:
  assumes "i < M"
  shows "Deriv (\<lambda>t. alpt t i)
               (\<lambda>t. - gn * (Ev t i * Ealpt t)
                    - gn * (Ev t i * (ea t / msq t)))"
proof (rule Deriv_cong)
  show "Deriv (\<lambda>t. alp t i - astar i)
              (\<lambda>t. (- gn * (Ev t i * Ealp t) - gn * (Ev t i * eps M t)) - 0)"
    by (rule Deriv_diff[OF H_sla[OF assms] Deriv_const])
next
  fix t show "alp t i - astar i = alpt t i" by (simp add: alpt_def)
next
  fix t
  show "(- gn * (Ev t i * Ealp t) - gn * (Ev t i * eps M t)) - 0
        = - gn * (Ev t i * Ealpt t) - gn * (Ev t i * (ea t / msq t))"
    by (simp add: Ealp_split algebra_simps)
qed

subsection \<open>4.57-4.58: Lyapunov analysis\<close>

text \<open>The dissertation's candidate (4.57) is built on the EXTENDED vector
  @{text "alphabar_f"} whose last entry is @{text "1 - vec1 alpha_f"}, so
  @{text "alphabartilde = [alphatilde ; -vec1 alphatilde]"}.  We treat both
  that function (@{text Vb}) and the reduced one (@{text Vr}) used by
  Narendra et al.\<close>

definition Vr :: "real \<Rightarrow> real"
  where "Vr = Wq M (\<lambda>_. 1) alpt"           \<comment> \<open>alphatilde^T alphatilde / 2\<close>

text \<open>Reduced Lyapunov function: the correct counterpart of (4.58), matching
  eq. (24) of Narendra-Wang-Chen.\<close>

theorem Vr_dyn:
  "Deriv Vr (\<lambda>t. - gn * (Ealpt t * Ealpt t)
                 - gn * (Ealpt t * (ea t / msq t)))"
  unfolding Vr_def
proof (rule Deriv_cong_deriv[OF Wq_deriv[OF alpt_dyn]])
  fix t
  have "(\<Sum>i<M. inverse 1 * (alpt t i *
          (- gn * (Ev t i * Ealpt t) - gn * (Ev t i * (ea t / msq t)))))
        = (\<Sum>i<M. (- gn * Ealpt t - gn * (ea t / msq t))
                  * (Ev t i * alpt t i))"
    by (rule sum.cong) (auto simp: algebra_simps)
  also have "\<dots> = (- gn * Ealpt t - gn * (ea t / msq t))
                  * (\<Sum>i<M. Ev t i * alpt t i)"
    by (simp add: sum_distrib_left)
  finally show "(\<Sum>i<M. inverse 1 * (alpt t i *
          (- gn * (Ev t i * Ealpt t) - gn * (Ev t i * (ea t / msq t)))))
        = - gn * (Ealpt t * Ealpt t) - gn * (Ealpt t * (ea t / msq t))"
    by (simp add: Ealpt_def algebra_simps)
qed

corollary Vr_nonincreasing:
  assumes Hea: "\<And>t. ea t = 0" and ab: "a \<le> b"
  shows "Vr b \<le> Vr a"
proof (rule nonincr_of_nonpos_deriv[OF Vr_dyn _ ab])
  fix t :: real
  have "0 \<le> gn * (Ealpt t * Ealpt t)"
    using H_gn by (simp add: mult_nonneg_nonneg)
  thus "- gn * (Ealpt t * Ealpt t) - gn * (Ealpt t * (ea t / msq t)) \<le> 0"
    by (simp add: Hea)
qed

text \<open>The dissertation's own candidate (4.57).\<close>

definition Sb :: "real \<Rightarrow> real"      \<comment> \<open>vec1 . alphatilde_f\<close>
  where "Sb t = (\<Sum>i<M. alpt t i)"

definition SE :: "real \<Rightarrow> real"      \<comment> \<open>vec1 . E_f\<close>
  where "SE t = (\<Sum>i<M. Ev t i)"

definition Vb :: "real \<Rightarrow> real"      \<comment> \<open>(4.57)\<close>
  where "Vb t = inverse (2 * gn)
                * ((\<Sum>i<M. alpt t i * alpt t i) + Sb t * Sb t)"

lemma Sb_dyn:
  "Deriv Sb (\<lambda>t. - gn * (SE t * Ealpt t)
                 - gn * (SE t * (ea t / msq t)))"
proof (rule Deriv_cong)
  show "Deriv (\<lambda>t. \<Sum>i<M. alpt t i)
              (\<lambda>t. \<Sum>i<M. - gn * (Ev t i * Ealpt t)
                          - gn * (Ev t i * (ea t / msq t)))"
    by (rule Deriv_sum[OF alpt_dyn])
next
  fix t show "(\<Sum>i<M. alpt t i) = Sb t" by (simp add: Sb_def)
next
  fix t
  have "(\<Sum>i<M. - gn * (Ev t i * Ealpt t)
                - gn * (Ev t i * (ea t / msq t)))
        = (\<Sum>i<M. (- gn * Ealpt t - gn * (ea t / msq t)) * Ev t i)"
    by (rule sum.cong) (auto simp: algebra_simps)
  also have "\<dots> = (- gn * Ealpt t - gn * (ea t / msq t)) * (\<Sum>i<M. Ev t i)"
    by (simp add: sum_distrib_left)
  finally show "(\<Sum>i<M. - gn * (Ev t i * Ealpt t)
                        - gn * (Ev t i * (ea t / msq t)))
                = - gn * (SE t * Ealpt t) - gn * (SE t * (ea t / msq t))"
    by (simp add: SE_def algebra_simps)
qed

text \<open>The polynomial identity behind (4.58), isolated as a statement about
  plain reals so that the normalising quotient @{text "e_alpha/m^2"} enters it
  as an atom and no division has to be simplified under a summation.\<close>

lemma Vb_algebra:
  fixes g A B S r :: real
  assumes g: "g \<noteq> 0"
  shows "inverse (2 * g) * ((- 2 * g * (A + r) * A)
           + ((- g * (S * A) - g * (S * r)) * B
              + B * (- g * (S * A) - g * (S * r))))
         = - ((A + B * S) * (A + r))"
proof -
  have E: "((- 2 * g * (A + r) * A)
           + ((- g * (S * A) - g * (S * r)) * B
              + B * (- g * (S * A) - g * (S * r))))
        = (2 * g) * (- ((A + B * S) * (A + r)))"
    by (simp add: algebra_simps)
  have inv: "inverse (2 * g) * (2 * g) = 1" using g by simp
  show ?thesis
    unfolding E using g by (simp add: mult.assoc[symmetric] inv)
qed

text \<open>The EXACT derivative of the dissertation's Lyapunov candidate (4.57).
  Compare with (4.58), which claims
  @{text "Vdot = -N alphatilde^T E^T E alphatilde
                 - N alphatilde^T E^T e_alpha/m^2"}.
  The cross term @{text "Sb * SE"} is what (4.58) replaces by the factor N.\<close>

theorem Vb_dyn:
  "Deriv Vb (\<lambda>t. - ((Ealpt t + Sb t * SE t) * (Ealpt t + ea t / msq t)))"
proof (rule Deriv_cong)
  have D1: "Deriv (\<lambda>t. alpt t i * alpt t i)
              (\<lambda>t. (- gn * (Ev t i * Ealpt t)
                    - gn * (Ev t i * (ea t / msq t))) * alpt t i
                   + alpt t i * (- gn * (Ev t i * Ealpt t)
                                 - gn * (Ev t i * (ea t / msq t))))"
    if "i < M" for i
    by (rule Deriv_mult[OF alpt_dyn[OF that] alpt_dyn[OF that]])
  have D2: "Deriv (\<lambda>t. Sb t * Sb t)
              (\<lambda>t. (- gn * (SE t * Ealpt t)
                    - gn * (SE t * (ea t / msq t))) * Sb t
                   + Sb t * (- gn * (SE t * Ealpt t)
                             - gn * (SE t * (ea t / msq t))))"
    by (rule Deriv_mult[OF Sb_dyn Sb_dyn])
  show "Deriv (\<lambda>t. inverse (2 * gn)
                   * ((\<Sum>i<M. alpt t i * alpt t i) + Sb t * Sb t))
              (\<lambda>t. inverse (2 * gn)
                   * ((\<Sum>i<M. (- gn * (Ev t i * Ealpt t)
                               - gn * (Ev t i * (ea t / msq t))) * alpt t i
                              + alpt t i * (- gn * (Ev t i * Ealpt t)
                                            - gn * (Ev t i * (ea t / msq t))))
                      + ((- gn * (SE t * Ealpt t)
                          - gn * (SE t * (ea t / msq t))) * Sb t
                         + Sb t * (- gn * (SE t * Ealpt t)
                                   - gn * (SE t * (ea t / msq t))))))"
    by (rule Deriv_scale[OF Deriv_add[OF Deriv_sum[OF D1] D2]])
next
  fix t show "inverse (2 * gn) * ((\<Sum>i<M. alpt t i * alpt t i) + Sb t * Sb t)
              = Vb t" by (simp add: Vb_def)
next
  fix t
  have "(\<Sum>i<M. (- gn * (Ev t i * Ealpt t)
                 - gn * (Ev t i * (ea t / msq t))) * alpt t i
                + alpt t i * (- gn * (Ev t i * Ealpt t)
                              - gn * (Ev t i * (ea t / msq t))))
        = (\<Sum>i<M. (- 2 * gn * (Ealpt t + ea t / msq t))
                  * (Ev t i * alpt t i))"
    by (rule sum.cong) (auto simp: algebra_simps)
  also have "\<dots> = (- 2 * gn * (Ealpt t + ea t / msq t))
                  * (\<Sum>i<M. Ev t i * alpt t i)"
    by (simp add: sum_distrib_left)
  finally have S: "(\<Sum>i<M. (- gn * (Ev t i * Ealpt t)
                 - gn * (Ev t i * (ea t / msq t))) * alpt t i
                + alpt t i * (- gn * (Ev t i * Ealpt t)
                              - gn * (Ev t i * (ea t / msq t))))
        = - 2 * gn * (Ealpt t + ea t / msq t) * Ealpt t"
    by (simp add: Ealpt_def algebra_simps)
  have gn0: "gn \<noteq> 0" using H_gn by simp
  show "inverse (2 * gn)
        * ((\<Sum>i<M. (- gn * (Ev t i * Ealpt t)
                    - gn * (Ev t i * (ea t / msq t))) * alpt t i
                   + alpt t i * (- gn * (Ev t i * Ealpt t)
                                 - gn * (Ev t i * (ea t / msq t))))
           + ((- gn * (SE t * Ealpt t)
               - gn * (SE t * (ea t / msq t))) * Sb t
              + Sb t * (- gn * (SE t * Ealpt t)
                        - gn * (SE t * (ea t / msq t)))))
        = - ((Ealpt t + Sb t * SE t) * (Ealpt t + ea t / msq t))"
    unfolding S by (rule Vb_algebra[OF gn0])
qed

subsection \<open>The factor N of (4.58) does not follow\<close>

text \<open>With @{text "e_alpha = 0"} the exact derivative is
  @{text "-(Ealphatilde + Sb SE) Ealphatilde"} while (4.58) asserts
  @{text "-N (Ealphatilde)^2"}.  These disagree, and the exact one is not even
  sign definite -- so (4.57)+(4.58) do NOT establish the boundedness of
  alphatilde_f claimed on page 66 of the dissertation.  Note in particular
  that the N-dependence of the convergence rate, which the dissertation reads
  off from (4.58), is not supported by the corrected identity @{thm Vb_dyn}.

  The fix is the reduced Lyapunov function @{term Vr}, for which
  @{thm Vr_dyn} gives a negative semi-definite derivative
  (@{thm Vr_nonincreasing}); this is exactly eq. (24) of Narendra-Wang-Chen,
  which the dissertation follows.  The stated qualitative conclusion of
  Section 4.3 is therefore correct; only the route through alphabartilde is
  not.\<close>

corollary Vb_deriv_differs_from_4_58:
  assumes "M = 2" and "ea t = 0" and "Ealpt t = 1"
      and "Sb t = 1" and "SE t = 1"
  shows "- ((Ealpt t + Sb t * SE t) * (Ealpt t + ea t / msq t))
         \<noteq> - (real (Suc M) * (Ealpt t * Ealpt t))"
  using assms by simp

corollary Vb_deriv_can_be_positive:
  assumes "ea t = 0" and "Ealpt t = 1" and "Sb t = - 2" and "SE t = 1"
  shows "0 < - ((Ealpt t + Sb t * SE t) * (Ealpt t + ea t / msq t))"
  using assms by simp

text \<open>A fully concrete witness, in terms of the underlying vectors rather than
  of the three scalars: with @{text "M = 2"} models beyond the last one,
  @{text "E_f = (2, -1)"} and @{text "alphatilde_f = (-1/3, -5/3)"}, the exact
  derivative (4.58) is aiming at is @{text "+1"} where (4.58) predicts
  @{text "-3"}.  (The other machine-checked ports of this development use the
  same witness.)\<close>

corollary Vb_deriv_positive_witness:
  assumes M2: "M = 2" and Hea: "ea t = 0"
      and E0: "Ev t 0 = 2" and E1: "Ev t 1 = - 1"
      and a0: "alpt t 0 = - 1/3" and a1: "alpt t 1 = - 5/3"
  shows "Ealpt t = 1 \<and> Sb t = - 2 \<and> SE t = 1
         \<and> - ((Ealpt t + Sb t * SE t) * (Ealpt t + ea t / msq t)) = 1
         \<and> - (real (Suc M) * (Ealpt t * Ealpt t)) = - 3"
proof -
  have H1: "Ealpt t = 1"
  proof -
    have "Ealpt t = (\<Sum>i<M. Ev t i * alpt t i)" by (simp add: Ealpt_def)
    also have "\<dots> = (\<Sum>i<2. Ev t i * alpt t i)" by (simp add: M2)
    also have "\<dots> = 1"
      by (simp add: lessThan_2 E0 E1 a0 a1 del: One_nat_def)
    finally show ?thesis .
  qed
  have H2: "Sb t = - 2"
  proof -
    have "Sb t = (\<Sum>i<M. alpt t i)" by (simp add: Sb_def)
    also have "\<dots> = (\<Sum>i<2. alpt t i)" by (simp add: M2)
    also have "\<dots> = - 2"
      by (simp add: lessThan_2 a0 a1 del: One_nat_def)
    finally show ?thesis .
  qed
  have H3: "SE t = 1"
  proof -
    have "SE t = (\<Sum>i<M. Ev t i)" by (simp add: SE_def)
    also have "\<dots> = (\<Sum>i<2. Ev t i)" by (simp add: M2)
    also have "\<dots> = 1"
      by (simp add: lessThan_2 E0 E1 del: One_nat_def)
    finally show ?thesis .
  qed
  show ?thesis using H1 H2 H3 by (simp add: Hea M2)
qed

end

section \<open>4.60-4.69: second level adaptation with a forgetting factor (SLAFF)\<close>

locale slaff_sig = second_level +
  fixes sig :: real                            \<comment> \<open>the forgetting factor sigma\<close>
    and Mf :: "real \<Rightarrow> nat \<Rightarrow> nat \<Rightarrow> real"     \<comment> \<open>M_f of (4.65)\<close>
    and vf :: "real \<Rightarrow> nat \<Rightarrow> real"            \<comment> \<open>v_f of (4.65)\<close>
    and alpF :: "real \<Rightarrow> nat \<Rightarrow> real"
begin

definition alpFt :: "real \<Rightarrow> nat \<Rightarrow> real"
  where "alpFt t i = alpF t i - astar i"

definition EalpF :: "real \<Rightarrow> real"
  where "EalpF t = (\<Sum>i<M. Ev t i * alpF t i)"

definition EalpFt :: "real \<Rightarrow> real"
  where "EalpFt t = (\<Sum>i<M. Ev t i * alpFt t i)"

definition qres :: "real \<Rightarrow> nat \<Rightarrow> real"   \<comment> \<open>the residual M_f alpha*_f + v_f\<close>
  where "qres t i = (\<Sum>j<M. Mf t i j * astar j) + vf t i"

definition MQ :: "(nat \<Rightarrow> real) \<Rightarrow> real \<Rightarrow> real"
  where "MQ x t = (\<Sum>i<M. x i * (\<Sum>j<M. Mf t i j * x j))"

definition EXv :: "(nat \<Rightarrow> real) \<Rightarrow> real \<Rightarrow> real"
  where "EXv x t = (\<Sum>i<M. Ev t i * x i)"

definition VrF :: "real \<Rightarrow> real"          \<comment> \<open>(4.68)\<close>
  where "VrF = Wq M (\<lambda>_. 1) alpFt"

end

locale slaff = slaff_sig +
  assumes H_sig: "0 < sig"
      and H_Mf0: "\<And>i j. Mf 0 i j = 0"
      and H_vf0: "\<And>i. vf 0 i = 0"
      and H_Mf: "\<And>i j. i < M \<Longrightarrow> j < M \<Longrightarrow>                        \<comment> \<open>(4.66)\<close>
            Deriv (\<lambda>t. Mf t i j) (\<lambda>t. - sig * Mf t i j + Ev t i * Ev t j)"
      and H_vf: "\<And>i. i < M \<Longrightarrow>                                   \<comment> \<open>(4.66)\<close>
            Deriv (\<lambda>t. vf t i) (\<lambda>t. - sig * vf t i + Ev t i * eps M t)"
      and H_slaff: "\<And>i. i < M \<Longrightarrow>                                \<comment> \<open>(4.67)\<close>
            Deriv (\<lambda>t. alpF t i)
                  (\<lambda>t. gn * (- (\<Sum>j<M. Mf t i j * alpF t j)
                             - Ev t i * EalpF t - vf t i - Ev t i * eps M t))"
begin

text \<open>(4.64)/(4.65) <-> (4.66): the integrating-factor identity.  Saying
  @{text "M_f(t) = int_0^t e^{-sigma (t-tau)} E^T E dtau"} with
  @{text "M_f(0) = 0"} is exactly saying that @{text "e^{sigma t} M_f(t)"} has
  derivative @{text "e^{sigma t} E^T E"}.\<close>

theorem Mf_integrating_factor:
  assumes "i < M" and "j < M"
  shows "Deriv (\<lambda>t. exp (sig * t) * Mf t i j)
               (\<lambda>t. exp (sig * t) * (Ev t i * Ev t j))"
proof (rule Deriv_cong_deriv)
  show "Deriv (\<lambda>t. exp (sig * t) * Mf t i j)
              (\<lambda>t. sig * exp (sig * t) * Mf t i j
                   + exp (sig * t) * (- sig * Mf t i j + Ev t i * Ev t j))"
    by (rule Deriv_mult[OF Deriv_exp_lin H_Mf[OF assms]])
qed (simp add: algebra_simps)

theorem vf_integrating_factor:
  assumes "i < M"
  shows "Deriv (\<lambda>t. exp (sig * t) * vf t i)
               (\<lambda>t. exp (sig * t) * (Ev t i * eps M t))"
proof (rule Deriv_cong_deriv)
  show "Deriv (\<lambda>t. exp (sig * t) * vf t i)
              (\<lambda>t. sig * exp (sig * t) * vf t i
                   + exp (sig * t) * (- sig * vf t i + Ev t i * eps M t))"
    by (rule Deriv_mult[OF Deriv_exp_lin H_vf[OF assms]])
qed (simp add: algebra_simps)

text \<open>@{text M_f} is positive semi-definite for all @{term "0 \<le> t"}.  This is
  what makes the quadratic term of (4.69) sign definite; the dissertation
  asserts it implicitly by writing @{text M_f} as a convolution integral of
  @{text "E^T E"}.\<close>

lemma MQ_dyn: "Deriv (MQ x) (\<lambda>t. - sig * MQ x t + EXv x t * EXv x t)"
proof (rule Deriv_cong)
  have Din: "Deriv (\<lambda>t. Mf t i j * x j)
                   (\<lambda>t. (- sig * Mf t i j + Ev t i * Ev t j) * x j
                        + Mf t i j * 0)"
    if "i < M" "j < M" for i j
    by (rule Deriv_mult[OF H_Mf[OF that] Deriv_const])
  have Dout: "Deriv (\<lambda>t. x i * (\<Sum>j<M. Mf t i j * x j))
                    (\<lambda>t. 0 * (\<Sum>j<M. Mf t i j * x j)
                         + x i * (\<Sum>j<M. (- sig * Mf t i j
                                          + Ev t i * Ev t j) * x j
                                         + Mf t i j * 0))"
    if "i < M" for i
    by (rule Deriv_mult[OF Deriv_const Deriv_sum[OF Din[OF that]]])
  show "Deriv (\<lambda>t. \<Sum>i<M. x i * (\<Sum>j<M. Mf t i j * x j))
              (\<lambda>t. \<Sum>i<M. 0 * (\<Sum>j<M. Mf t i j * x j)
                          + x i * (\<Sum>j<M. (- sig * Mf t i j
                                           + Ev t i * Ev t j) * x j
                                          + Mf t i j * 0))"
    by (rule Deriv_sum[OF Dout])
next
  fix t show "(\<Sum>i<M. x i * (\<Sum>j<M. Mf t i j * x j)) = MQ x t"
    by (simp add: MQ_def)
next
  fix t
  have inner: "(\<Sum>j<M. (- sig * Mf t i j + Ev t i * Ev t j) * x j
                       + Mf t i j * 0)
               = - sig * (\<Sum>j<M. Mf t i j * x j)
                 + Ev t i * (\<Sum>j<M. Ev t j * x j)" for i
  proof -
    have "(\<Sum>j<M. (- sig * Mf t i j + Ev t i * Ev t j) * x j + Mf t i j * 0)
          = (\<Sum>j<M. (- sig) * (Mf t i j * x j) + Ev t i * (Ev t j * x j))"
      by (rule sum.cong) (auto simp: algebra_simps)
    also have "\<dots> = (\<Sum>j<M. (- sig) * (Mf t i j * x j))
                    + (\<Sum>j<M. Ev t i * (Ev t j * x j))"
      by (rule sum.distrib)
    finally show ?thesis by (simp add: sum_distrib_left)
  qed
  have "(\<Sum>i<M. 0 * (\<Sum>j<M. Mf t i j * x j)
                + x i * (\<Sum>j<M. (- sig * Mf t i j + Ev t i * Ev t j) * x j
                                + Mf t i j * 0))
        = (\<Sum>i<M. (- sig) * (x i * (\<Sum>j<M. Mf t i j * x j))
                  + (\<Sum>j<M. Ev t j * x j) * (Ev t i * x i))"
  proof (rule sum.cong[OF refl])
    fix i assume "i \<in> {..<M}"
    show "0 * (\<Sum>j<M. Mf t i j * x j)
          + x i * (\<Sum>j<M. (- sig * Mf t i j + Ev t i * Ev t j) * x j
                            + Mf t i j * 0)
          = (- sig) * (x i * (\<Sum>j<M. Mf t i j * x j))
            + (\<Sum>j<M. Ev t j * x j) * (Ev t i * x i)"
      by (simp only: inner) (simp add: algebra_simps)
  qed
  also have "\<dots> = (- sig) * (\<Sum>i<M. x i * (\<Sum>j<M. Mf t i j * x j))
                  + (\<Sum>j<M. Ev t j * x j) * (\<Sum>i<M. Ev t i * x i)"
    by (simp add: sum.distrib sum_distrib_left)
  finally show "(\<Sum>i<M. 0 * (\<Sum>j<M. Mf t i j * x j)
                + x i * (\<Sum>j<M. (- sig * Mf t i j + Ev t i * Ev t j) * x j
                                + Mf t i j * 0))
        = - sig * MQ x t + EXv x t * EXv x t"
    by (simp add: MQ_def EXv_def)
qed

theorem Mf_psd:
  assumes t: "0 \<le> t"
  shows "0 \<le> MQ x t"
proof -
  have Hexp: "Deriv (\<lambda>t. exp (sig * t) * MQ x t)
                    (\<lambda>t. exp (sig * t) * (EXv x t * EXv x t))"
  proof (rule Deriv_cong_deriv)
    show "Deriv (\<lambda>t. exp (sig * t) * MQ x t)
                (\<lambda>t. sig * exp (sig * t) * MQ x t
                     + exp (sig * t) * (- sig * MQ x t + EXv x t * EXv x t))"
      by (rule Deriv_mult[OF Deriv_exp_lin MQ_dyn])
  qed (simp add: algebra_simps)
  have Hq0: "MQ x 0 = 0" by (simp add: MQ_def H_Mf0)
  have "exp (sig * 0) * MQ x 0 \<le> exp (sig * t) * MQ x t"
  proof (rule nondecr_of_nonneg_deriv[OF Hexp _ t])
    fix s :: real
    have "0 \<le> exp (sig * s)" by simp
    moreover have "0 \<le> EXv x s * EXv x s" by (rule zero_le_square)
    ultimately show "0 \<le> exp (sig * s) * (EXv x s * EXv x s)"
      by (rule mult_nonneg_nonneg)
  qed
  hence "0 \<le> exp (sig * t) * MQ x t" by (simp add: Hq0)
  thus ?thesis using exp_gt_zero[of "sig * t"] by (simp add: zero_le_mult_iff)
qed

subsection \<open>The SLAFF adaptive law (4.67)\<close>

lemma EalpF_split: "EalpF t = EalpFt t + (- eps M t + ea t / msq t)"
proof -
  have "EalpFt t = (\<Sum>i<M. Ev t i * alpF t i) - (\<Sum>i<M. Ev t i * astar i)"
    by (simp add: EalpFt_def alpFt_def sum_subtractf algebra_simps)
  thus ?thesis by (simp add: EalpF_def E_alpha_star)
qed

lemma Mf_alpF_split:
  "(\<Sum>j<M. Mf t i j * alpF t j)
   = (\<Sum>j<M. Mf t i j * alpFt t j) + (\<Sum>j<M. Mf t i j * astar j)"
  by (simp add: alpFt_def sum.distrib[symmetric] algebra_simps)

text \<open>The SLAFF parametric-error dynamics -- the correct counterpart of the
  step between (4.67) and (4.69).\<close>

theorem alpFt_dyn:
  assumes "i < M"
  shows "Deriv (\<lambda>t. alpFt t i)
               (\<lambda>t. gn * (- (\<Sum>j<M. Mf t i j * alpFt t j)
                          - Ev t i * EalpFt t
                          - Ev t i * (ea t / msq t)
                          - qres t i))"
proof (rule Deriv_cong)
  show "Deriv (\<lambda>t. alpF t i - astar i)
              (\<lambda>t. gn * (- (\<Sum>j<M. Mf t i j * alpF t j)
                         - Ev t i * EalpF t - vf t i - Ev t i * eps M t) - 0)"
    by (rule Deriv_diff[OF H_slaff[OF assms] Deriv_const])
next
  fix t show "alpF t i - astar i = alpFt t i" by (simp add: alpFt_def)
next
  fix t
  have "gn * (- (\<Sum>j<M. Mf t i j * alpF t j)
              - Ev t i * EalpF t - vf t i - Ev t i * eps M t) - 0
        = gn * (- ((\<Sum>j<M. Mf t i j * alpFt t j)
                   + (\<Sum>j<M. Mf t i j * astar j))
                - Ev t i * (EalpFt t + (- eps M t + ea t / msq t))
                - vf t i - Ev t i * eps M t) - 0"
    by (simp only: Mf_alpF_split EalpF_split)
  also have "\<dots> = gn * (- (\<Sum>j<M. Mf t i j * alpFt t j)
                        - Ev t i * EalpFt t
                        - Ev t i * (ea t / msq t)
                        - ((\<Sum>j<M. Mf t i j * astar j) + vf t i))"
    by (simp add: algebra_simps)
  finally show "gn * (- (\<Sum>j<M. Mf t i j * alpF t j)
              - Ev t i * EalpF t - vf t i - Ev t i * eps M t) - 0
        = gn * (- (\<Sum>j<M. Mf t i j * alpFt t j) - Ev t i * EalpFt t
                - Ev t i * (ea t / msq t) - qres t i)"
    by (simp add: qres_def)
qed

text \<open>When theta*_p is in the convex hull (so @{text "e_alpha = 0"}), the
  residual @{text "M_f alpha*_f + v_f"} vanishes identically, and the extra
  term of (4.69) disappears.\<close>

lemma qres_dyn:
  assumes i: "i < M"
  shows "Deriv (\<lambda>t. qres t i)
               (\<lambda>t. - sig * qres t i + Ev t i * (ea t / msq t))"
proof (rule Deriv_cong)
  have D1: "Deriv (\<lambda>t. Mf t i j * astar j)
                  (\<lambda>t. (- sig * Mf t i j + Ev t i * Ev t j) * astar j
                       + Mf t i j * 0)"
    if "j < M" for j
    by (rule Deriv_mult[OF H_Mf[OF i that] Deriv_const])
  show "Deriv (\<lambda>t. (\<Sum>j<M. Mf t i j * astar j) + vf t i)
              (\<lambda>t. (\<Sum>j<M. (- sig * Mf t i j + Ev t i * Ev t j) * astar j
                           + Mf t i j * 0)
                   + (- sig * vf t i + Ev t i * eps M t))"
    by (rule Deriv_add[OF Deriv_sum[OF D1] H_vf[OF i]])
next
  fix t show "(\<Sum>j<M. Mf t i j * astar j) + vf t i = qres t i"
    by (simp add: qres_def)
next
  fix t
  have "(\<Sum>j<M. (- sig * Mf t i j + Ev t i * Ev t j) * astar j
                + Mf t i j * 0)
        = (\<Sum>j<M. (- sig) * (Mf t i j * astar j)
                  + Ev t i * (Ev t j * astar j))"
    by (rule sum.cong) (auto simp: algebra_simps)
  also have "\<dots> = (- sig) * (\<Sum>j<M. Mf t i j * astar j)
                  + Ev t i * (\<Sum>j<M. Ev t j * astar j)"
    by (rule sum_comb)
  finally have C: "(\<Sum>j<M. (- sig * Mf t i j + Ev t i * Ev t j) * astar j
                            + Mf t i j * 0)
                   = (- sig) * (\<Sum>j<M. Mf t i j * astar j)
                     + Ev t i * (\<Sum>j<M. Ev t j * astar j)" .
  have EA: "(\<Sum>j<M. Ev t j * astar j) = - eps M t + ea t / msq t"
    by (rule E_alpha_star)
  show "(\<Sum>j<M. (- sig * Mf t i j + Ev t i * Ev t j) * astar j
                        + Mf t i j * 0)
                + (- sig * vf t i + Ev t i * eps M t)
                = - sig * qres t i + Ev t i * (ea t / msq t)"
    unfolding C EA qres_def by (simp add: algebra_simps)
qed

theorem qres_zero:
  assumes Hea: "\<And>t. ea t = 0" and t: "0 \<le> t" and i: "i < M"
  shows "qres t i = 0"
proof (rule quad_zero[where c = "\<lambda>_. 1" and T = qres
        and W' = "\<lambda>t. - sig * (\<Sum>i<M. qres t i * qres t i)"])
  show "\<And>j. j < M \<Longrightarrow> (0::real) < 1" by simp
next
  show "Deriv (Wq M (\<lambda>_. 1) qres)
              (\<lambda>t. - sig * (\<Sum>i<M. qres t i * qres t i))"
  proof (rule Deriv_cong_deriv[OF Wq_deriv[OF qres_dyn]])
    fix t
    have "(\<Sum>i<M. inverse 1
                  * (qres t i * (- sig * qres t i + Ev t i * (ea t / msq t))))
          = (\<Sum>i<M. (- sig) * (qres t i * qres t i))"
      by (rule sum.cong) (auto simp: Hea algebra_simps)
    also have "\<dots> = - sig * (\<Sum>i<M. qres t i * qres t i)"
      by (simp add: sum_distrib_left)
    finally show "(\<Sum>i<M. inverse 1
                    * (qres t i * (- sig * qres t i
                                   + Ev t i * (ea t / msq t))))
                  = - sig * (\<Sum>i<M. qres t i * qres t i)" .
  qed
next
  fix s :: real
  have "0 \<le> (\<Sum>i<M. qres s i * qres s i)" by (simp add: sum_nonneg)
  moreover have "0 \<le> sig" using H_sig by simp
  ultimately have "0 \<le> sig * (\<Sum>i<M. qres s i * qres s i)"
    by (rule mult_nonneg_nonneg[rotated])
  thus "- sig * (\<Sum>i<M. qres s i * qres s i) \<le> 0" by simp
next
  show "\<And>i. i < M \<Longrightarrow> qres 0 i = 0" by (simp add: qres_def H_Mf0 H_vf0)
next
  show "0 \<le> t" by (rule t)
next
  show "i < M" by (rule i)
qed

subsection \<open>4.68-4.69: Lyapunov analysis of SLAFF\<close>

text \<open>(4.68) is the same candidate as (4.57).  Below is the exact derivative
  for the REDUCED function.  As for (4.58), the factor N of (4.69) does not
  follow; and (4.69) additionally OMITS @{text v_f} from its residual term:
  it writes @{text "-N alphatilde^T M_f alpha*_f"} where the correct residual
  is @{text "M_f alpha*_f + v_f"} (@{term qres}), because
  @{text "E^T (E alpha*_f + eps_N) = E^T e_alpha/m^2"} mixes both.  The text's
  own justification one line later,
  @{text "N alphatilde^T M_f alpha*_f
          = N int e^{-sigma(t-tau)} E^T e_alpha dtau"},
  is the value of @{text "M_f alpha*_f + v_f"}, not of
  @{text "M_f alpha*_f"}, so the intent is right and only the written
  expression is incomplete.\<close>

theorem VrF_dyn:
  "Deriv VrF (\<lambda>t. gn * (- (\<Sum>i<M. alpFt t i * (\<Sum>j<M. Mf t i j * alpFt t j))
                        - EalpFt t * EalpFt t
                        - EalpFt t * (ea t / msq t)
                        - (\<Sum>i<M. alpFt t i * qres t i)))"
  unfolding VrF_def
proof (rule Deriv_cong_deriv[OF Wq_deriv[OF alpFt_dyn]])
  fix t
  have "(\<Sum>i<M. inverse 1 * (alpFt t i *
           (gn * (- (\<Sum>j<M. Mf t i j * alpFt t j) - Ev t i * EalpFt t
                  - Ev t i * (ea t / msq t) - qres t i))))
        = (\<Sum>i<M. (- gn) * (alpFt t i * (\<Sum>j<M. Mf t i j * alpFt t j))
                  + ((- gn) * (alpFt t i * qres t i)
                     + (gn * (- EalpFt t - ea t / msq t))
                       * (Ev t i * alpFt t i)))"
    by (rule sum.cong) (auto simp: algebra_simps)
  also have "\<dots> = (- gn) * (\<Sum>i<M. alpFt t i
                                   * (\<Sum>j<M. Mf t i j * alpFt t j))
                  + ((- gn) * (\<Sum>i<M. alpFt t i * qres t i)
                     + (gn * (- EalpFt t - ea t / msq t))
                       * (\<Sum>i<M. Ev t i * alpFt t i))"
    by (rule sum_comb3)
  finally show "(\<Sum>i<M. inverse 1 * (alpFt t i *
           (gn * (- (\<Sum>j<M. Mf t i j * alpFt t j) - Ev t i * EalpFt t
                  - Ev t i * (ea t / msq t) - qres t i))))
        = gn * (- (\<Sum>i<M. alpFt t i * (\<Sum>j<M. Mf t i j * alpFt t j))
                - EalpFt t * EalpFt t - EalpFt t * (ea t / msq t)
                - (\<Sum>i<M. alpFt t i * qres t i))"
    by (simp add: EalpFt_def algebra_simps)
qed

text \<open>With @{text "e_alpha = 0"} the derivative is negative semi-definite: the
  quadratic form in @{text M_f} is PSD (@{thm Mf_psd}) and the residual
  vanishes (@{thm qres_zero}).  This is the content that (4.69) intends.\<close>

theorem VrF_nonpos:
  assumes Hea: "\<And>t. ea t = 0" and t: "0 \<le> t"
  shows "gn * (- (\<Sum>i<M. alpFt t i * (\<Sum>j<M. Mf t i j * alpFt t j))
               - EalpFt t * EalpFt t
               - EalpFt t * (ea t / msq t)
               - (\<Sum>i<M. alpFt t i * qres t i)) \<le> 0"
proof -
  have R: "(\<Sum>i<M. alpFt t i * qres t i) = 0"
    by (simp add: qres_zero[OF Hea t])
  have P: "0 \<le> (\<Sum>i<M. alpFt t i * (\<Sum>j<M. Mf t i j * alpFt t j))"
    using Mf_psd[OF t, of "alpFt t"] by (simp add: MQ_def)
  have Q: "0 \<le> EalpFt t * EalpFt t" by (rule zero_le_square)
  have "gn * (- (\<Sum>i<M. alpFt t i * (\<Sum>j<M. Mf t i j * alpFt t j))
              - EalpFt t * EalpFt t - EalpFt t * (ea t / msq t)
              - (\<Sum>i<M. alpFt t i * qres t i))
        = - (gn * ((\<Sum>i<M. alpFt t i * (\<Sum>j<M. Mf t i j * alpFt t j))
                   + EalpFt t * EalpFt t))"
    by (simp add: R Hea algebra_simps)
  moreover have "0 \<le> gn * ((\<Sum>i<M. alpFt t i
                                   * (\<Sum>j<M. Mf t i j * alpFt t j))
                           + EalpFt t * EalpFt t)"
    using H_gn P Q by simp
  ultimately show ?thesis by simp
qed

end

end
