/-
# Chapter 4 (equations 4.1–4.69): second level adaptation as a parameter
# estimation technique

Lean 4 port of `coq/SLA_Chapter4.v`.

Everything in Chapter 4 that is a *mathematical statement* rather than a
modelling assumption or an asymptotic argument invoking Barbalat's lemma /
persistency of excitation is formalised:

| eqs.      | content                                                            |
|-----------|--------------------------------------------------------------------|
| 4.1–4.9   | plant, filters, linear parametrisation → the field `hparam`         |
| 4.10–4.15 | first-level regression model, error, normalisation, `e = θ̃ᵀφ`      |
| 4.16–4.23 | normalised gradient law and its Lyapunov function                   |
| 4.24–4.30 | the `N` first-level models and the dynamics of `e_{i,f}`            |
| 4.31–4.40 | convex combination / virtual model                                  |
| 4.41–4.45 | the `α*` parametrisation and invariance of the convex hull          |
| 4.46–4.51 | elimination of `α_N`: `E_f α*_f = −ε_{N,f}`                         |
| 4.52–4.58 | Lyapunov analysis of second level adaptation                        |
| 4.60–4.67 | forgetting factor: `M_f`, `v_f` and the SLAFF law                   |
| 4.68–4.69 | Lyapunov analysis of SLAFF                                          |

Statements 4.1–4.7 and 4.9 only fix *notation* for the filters generating `φ`;
their whole mathematical content downstream is that `φ` is differentiable and
that `z = θ*ᵖᵀφ`, which is exactly the field `hparam` (4.8).

**Two results of the dissertation do not hold as stated**; both are *proved*
here, not assumed — see `Vb_deriv`, `Vb_deriv_differs_from_4_58`,
`Vb_deriv_can_be_positive` and the comment above `VrF_deriv`.

Indexing: the `N` models are indexed by `Fin (M+1)`, so `N = M + 1` holds by
construction and the "last" model `N` of the text is `Fin.last M`.  The
second-level regressor `E_f` is then indexed by `Fin M`, and the split
`∑_{i<N} = ∑_{i<M} + (last)` used all over the chapter is Mathlib's
`Fin.sum_univ_castSucc`.
-/
import SLA.Prelim

open scoped Matrix

noncomputable section

namespace SLA

/-- The data of Chapter 4: the plant (4.1)–(4.9), the `N = M + 1` first-level
regression models (4.24) and the normalised gradient law (4.19)/(4.29). -/
structure Model (d M : ℕ) where
  /-- the regressor `φ(t) ∈ ℝ^d` generated by the filters (4.6)–(4.7) -/
  φ : ℝ → Fin d → ℝ
  /-- its time derivative `φ̇` -/
  φ' : ℝ → Fin d → ℝ
  /-- `θ*ᵖ`, the true (constant) parameter vector; `d = 2n` -/
  θstar : Fin d → ℝ
  /-- the filtered output `z(t)` of (4.9) -/
  z : ℝ → ℝ
  /-- the estimates `θ̂_{i,f}(t)` of the `N = M+1` first-level models -/
  θ : Fin (M + 1) → ℝ → Fin d → ℝ
  /-- the diagonal adaptation gain `Γ = Γᵀ > 0` of (4.17) -/
  γ : Fin d → ℝ
  /-- `φ` is differentiable with derivative `φ'` -/
  hφ : ∀ j, Deriv (fun t => φ t j) (fun t => φ' t j)
  /-- (4.8): the plant is linearly parametrised, `z = θ*ᵖᵀ φ` -/
  hparam : ∀ t, z t = θstar ⬝ᵥ φ t
  /-- `Γ > 0` -/
  hγ : ∀ j, 0 < γ j
  /-- (4.19)/(4.29): the normalised gradient law `θ̂̇_{i,f} = −Γ ε_{i,f} φ`,
  written out with `ε = (θ̂ᵀφ − z)/(1 + φᵀφ)` because the abbreviations are
  introduced only after the structure. -/
  hlaw : ∀ i j, Deriv (fun t => θ i t j)
    (fun t => -(γ j * ((θ i t ⬝ᵥ φ t - z t) / (1 + φ t ⬝ᵥ φ t)) * φ t j))
  /-- **The amended design rule `N = 2n + 1 = d + 1`** (page 64; the dissertation
  writes `N ≥ 2n + 1`).  Here `N = M + 1` by construction, so this says `M = d`.

  None of the *identities* below needs it — they consume only the existence of
  some `α*` with `Σ α* = 1` and `θ*ᵖ = Σ θ̂ᵢ(0) α*ᵢ`.  What needs it is
  **identifiability**: the second level regresses onto `α*_f`, so `α*_f` has to
  be a single point, and the coefficients are unique exactly when `N = d + 1`
  (`AppendixA.design_rule_exact`); at `N = d + 2` they already are not
  (`AppendixA.more_vertices_not_unique`).  See `../NOTE_convex_uniqueness.md`. -/
  hN_exact : M + 1 = d + 1

namespace Model

variable {d M : ℕ} (S : Model d M)

/-! ## 4.10–4.15 and 4.24–4.28: the first-level regression models -/

/-- (4.12): `m² = 1 + n_s² = 1 + φᵀφ`, the normalising signal. -/
def msq (t : ℝ) : ℝ := 1 + S.φ t ⬝ᵥ S.φ t

/-- (4.10)/(4.24): `ẑ_{i,f} = θ̂_{i,f}ᵀ φ`. -/
def zh (i : Fin (M + 1)) (t : ℝ) : ℝ := S.θ i t ⬝ᵥ S.φ t

/-- (4.11)/(4.25): `e_{i,f} = ẑ_{i,f} − z`. -/
def e (i : Fin (M + 1)) (t : ℝ) : ℝ := S.zh i t - S.z t

/-- (4.14)/(4.26): `θ̃_{i,f} = θ̂_{i,f} − θ*ᵖ`. -/
def tht (i : Fin (M + 1)) (t : ℝ) : Fin d → ℝ := S.θ i t - S.θstar

/-- (4.13)/(4.27): `ε_{i,f} = e_{i,f}/m²`. -/
def eps (i : Fin (M + 1)) (t : ℝ) : ℝ := S.e i t / S.msq t

theorem msq_pos (t : ℝ) : 0 < S.msq t := by
  have := dotProduct_self_nonneg (S.φ t)
  unfold msq
  linarith

theorem msq_ne_zero (t : ℝ) : S.msq t ≠ 0 := (S.msq_pos t).ne'

/-- (4.19)/(4.29) in terms of `ε`. -/
theorem law (i : Fin (M + 1)) (j : Fin d) :
    Deriv (fun t => S.θ i t j) (fun t => -(S.γ j * S.eps i t * S.φ t j)) := S.hlaw i j

/-- **(4.15)/(4.28)**: the identification error is the linear form in the
parametric error, `e_{i,f} = θ̃_{i,f}ᵀ φ`. -/
theorem e_eq_dot_tht (i : Fin (M + 1)) (t : ℝ) : S.e i t = S.tht i t ⬝ᵥ S.φ t := by
  simp [e, zh, tht, S.hparam t, sub_dotProduct]

/-- **(4.15)/(4.28)** for the normalised error. -/
theorem eps_eq_dot_tht (i : Fin (M + 1)) (t : ℝ) :
    S.eps i t = (S.tht i t ⬝ᵥ S.φ t) / S.msq t := by
  rw [eps, e_eq_dot_tht]

theorem e_eq_eps_mul_msq (i : Fin (M + 1)) (t : ℝ) : S.e i t = S.eps i t * S.msq t := by
  have hm : S.msq t ≠ 0 := S.msq_ne_zero t
  rw [eps]
  field_simp

/-! ## 4.16–4.21: the normalised gradient law -/

/-- **(4.20)/(4.21)**: `θ*ᵖ` is constant, so the parametric error moves exactly
like the estimate. -/
theorem tht_law (i : Fin (M + 1)) (j : Fin d) :
    Deriv (fun t => S.tht i t j) (fun t => -(S.γ j * S.eps i t * S.φ t j)) := by
  simpa [tht] using (S.law i j).sub_const (S.θstar j)

/-- The computation behind (4.23), (4.30) and (4.44): along a gradient law with
error signal `E`, the quadratic form `½ Tᵀ Γ⁻¹ T` has derivative `−E · (Tᵀφ)`. -/
theorem grad_Wq_deriv (T : ℝ → Fin d → ℝ) (E : ℝ → ℝ)
    (hT : ∀ j, Deriv (fun t => T t j) (fun t => -(S.γ j * E t * S.φ t j))) :
    Deriv (Wq S.γ T) (fun t => -(E t * (T t ⬝ᵥ S.φ t))) := by
  refine (Wq_hasDeriv hT).congr (fun _ => rfl) fun t => ?_
  have h : ∀ j, (S.γ j)⁻¹ * (T t j * -(S.γ j * E t * S.φ t j)) = -E t * (T t j * S.φ t j) := by
    intro j
    have hj : S.γ j ≠ 0 := (S.hγ j).ne'
    field_simp
  rw [Finset.sum_congr rfl fun j _ => h j, ← Finset.mul_sum]
  unfold dotProduct
  ring

/-! ## 4.22–4.23: stability of the first-level estimator -/

/-- (4.22): `V(θ̃_{i,f}) = θ̃ᵀ Γ⁻¹ θ̃ / 2`. -/
def V1 (i : Fin (M + 1)) : ℝ → ℝ := Wq S.γ (S.tht i)

/-- **(4.23)**: `V̇ = −ε_{i,f}² m² ≤ 0`. -/
theorem V1_deriv (i : Fin (M + 1)) :
    Deriv (S.V1 i) (fun t => -(S.eps i t * S.eps i t * S.msq t)) := by
  refine (S.grad_Wq_deriv (S.tht i) (S.eps i) (S.tht_law i)).congr (fun _ => rfl) fun t => ?_
  rw [← S.e_eq_dot_tht, S.e_eq_eps_mul_msq]
  ring

theorem V1_antitone (i : Fin (M + 1)) : Antitone (S.V1 i) :=
  (S.V1_deriv i).antitone fun t => by
    have h := S.msq_pos t
    nlinarith [mul_self_nonneg (S.eps i t)]

/-! ## 4.30: dynamics of the identification errors -/

/-- `φᵀ Γ φ`. -/
def phiGphi (t : ℝ) : ℝ := ∑ j, S.γ j * (S.φ t j * S.φ t j)

theorem gen_e_deriv (T : ℝ → Fin d → ℝ) (E : ℝ → ℝ)
    (hT : ∀ j, Deriv (fun t => T t j) (fun t => -(S.γ j * E t * S.φ t j))) :
    Deriv (fun t => T t ⬝ᵥ S.φ t) (fun t => -(E t * S.phiGphi t) + T t ⬝ᵥ S.φ' t) := by
  have key : Deriv (fun t => ∑ j, T t j * S.φ t j)
      (fun t => ∑ j, (-(S.γ j * E t * S.φ t j) * S.φ t j + T t j * S.φ' t j)) :=
    Deriv.sum Finset.univ _ _ fun j _ => (hT j).mul (S.hφ j)
  refine key.congr (fun _ => rfl) fun t => ?_
  have h1 : ∑ j, -(S.γ j * E t * S.φ t j) * S.φ t j = -(E t * S.phiGphi t) := by
    have h : ∀ j, -(S.γ j * E t * S.φ t j) * S.φ t j
        = -E t * (S.γ j * (S.φ t j * S.φ t j)) := fun j => by ring
    rw [Finset.sum_congr rfl fun j _ => h j, ← Finset.mul_sum, phiGphi]
    ring
  rw [Finset.sum_add_distrib, h1]
  rfl

/-- **(4.30)**: `ė_{i,f} = −ε_{i,f} φᵀΓφ + θ̃_{i,f}ᵀ φ̇`. -/
theorem e_deriv (i : Fin (M + 1)) :
    Deriv (S.e i) (fun t => -(S.eps i t * S.phiGphi t) + S.tht i t ⬝ᵥ S.φ' t) :=
  (S.gen_e_deriv (S.tht i) (S.eps i) (S.tht_law i)).congr
    (fun t => (S.e_eq_dot_tht i t).symm) fun _ => rfl

/-! ## 4.31–4.40: convex combinations and the virtual model -/

section Convex

variable (β : Fin (M + 1) → ℝ)

/-- (4.31): `θ̂_{v,f} = ∑ᵢ θ̂_{i,f} βᵢ`. -/
def thv (t : ℝ) : Fin d → ℝ := fun j => ∑ i, S.θ i t j * β i

/-- (4.32): the output of the virtual model. -/
def zhv (t : ℝ) : ℝ := S.thv β t ⬝ᵥ S.φ t

/-- (4.33): its identification error. -/
def ev (t : ℝ) : ℝ := S.zhv β t - S.z t

/-- (4.34): its parametric error. -/
def thtv (t : ℝ) : Fin d → ℝ := S.thv β t - S.θstar

/-- the normalised error of the virtual model -/
def epsv (t : ℝ) : ℝ := S.ev β t / S.msq t

/-- A linear combination of the estimates produces the same linear combination
of the model outputs.  Used for (4.32) and (4.42). -/
theorem dot_lincomb (c : Fin (M + 1) → ℝ) (t : ℝ) :
    (fun j => ∑ i, S.θ i t j * c i) ⬝ᵥ S.φ t = ∑ i, S.zh i t * c i := by
  simp only [dotProduct, zh, Finset.sum_mul]
  rw [Finset.sum_comm]
  exact Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => by ring

theorem zhv_eq (t : ℝ) : S.zhv β t = ∑ i, S.zh i t * β i := S.dot_lincomb β t

theorem ev_eq_dot_thtv (t : ℝ) : S.ev β t = S.thtv β t ⬝ᵥ S.φ t := by
  simp [ev, zhv, thtv, S.hparam t, sub_dotProduct]

variable (hβ : ∑ i, β i = 1)

include hβ

/-- **(4.35)**: the parametric error of the virtual model is the *same* convex
combination of the parametric errors of the first-level models. -/
theorem thtv_convex (t : ℝ) (j : Fin d) : S.thtv β t j = ∑ i, S.tht i t j * β i := by
  have h : ∑ i, S.tht i t j * β i = (∑ i, S.θ i t j * β i) - S.θstar j * ∑ i, β i := by
    simp only [tht, Pi.sub_apply, Finset.mul_sum, ← Finset.sum_sub_distrib]
    exact Finset.sum_congr rfl fun i _ => by ring
  rw [h, hβ, thtv, Pi.sub_apply, thv]
  ring

/-- **(4.37) = (4.39)**: the identification error of the virtual model is
*identically* the convex combination of the first-level errors.

The dissertation argues (between 4.37 and 4.40) that the two only converge to
each other exponentially, and coincide when `e_v(0) = ∑ βᵢ eᵢ(0)`.  With linear
regression models they are equal by construction, with no condition on initial
values. -/
theorem ev_convex (t : ℝ) : S.ev β t = ∑ i, S.e i t * β i := by
  have h : ∑ i, S.e i t * β i = (∑ i, S.zh i t * β i) - S.z t * ∑ i, β i := by
    simp only [e, Finset.mul_sum, ← Finset.sum_sub_distrib]
    exact Finset.sum_congr rfl fun i _ => by ring
  rw [h, hβ, ev, S.zhv_eq β]
  ring

theorem epsv_convex (t : ℝ) : S.epsv β t = ∑ i, S.eps i t * β i := by
  rw [epsv, S.ev_convex β hβ t, Finset.sum_div]
  exact Finset.sum_congr rfl fun i _ => by rw [eps]; ring

/-- **(4.36)/(4.40)**: the virtual model obeys an adaptive law of exactly the
same form as the first-level models. -/
theorem thv_law (j : Fin d) :
    Deriv (fun t => S.thv β t j) (fun t => -(S.γ j * S.epsv β t * S.φ t j)) := by
  have key : Deriv (fun t => ∑ i, S.θ i t j * β i)
      (fun t => ∑ i, -(S.γ j * S.eps i t * S.φ t j) * β i) :=
    Deriv.sum Finset.univ _ _ fun i _ => (S.law i j).mul_const (β i)
  refine key.congr (fun _ => rfl) fun t => ?_
  have h : ∀ i, -(S.γ j * S.eps i t * S.φ t j) * β i
      = -(S.γ j * S.φ t j) * (S.eps i t * β i) := fun i => by ring
  rw [Finset.sum_congr rfl fun i _ => h i, ← Finset.mul_sum, ← S.epsv_convex β hβ t]
  ring

theorem thtv_law (j : Fin d) :
    Deriv (fun t => S.thtv β t j) (fun t => -(S.γ j * S.epsv β t * S.φ t j)) := by
  simpa [thtv] using (S.thv_law β hβ j).sub_const (S.θstar j)

/-- **(4.37) = (4.39)**: the two error dynamics coincide. -/
theorem ev_deriv :
    Deriv (S.ev β) (fun t => -(S.epsv β t * S.phiGphi t) + S.thtv β t ⬝ᵥ S.φ' t) :=
  (S.gen_e_deriv (S.thtv β) (S.epsv β) (S.thtv_law β hβ)).congr
    (fun t => (S.ev_eq_dot_thtv β t).symm) fun _ => rfl

end Convex

/-! ## 4.46–4.51: elimination of `α_N`

With `Fin (M+1)`-indexed models the last model is `Fin.last M`. -/

/-- (4.50): `E_f = [ε₁ − ε_N, …, ε_{N−1} − ε_N]`. -/
def Ev (t : ℝ) (i : Fin M) : ℝ := S.eps i.castSucc t - S.eps (Fin.last M) t

/-- `1⃗ ⬝ E_f`, the row sum of the second-level regressor. -/
def SE (t : ℝ) : ℝ := ∑ i, S.Ev t i

/-- `E_f x`, the second-level regressor applied to a fixed vector `x`. -/
def EX (x : Fin M → ℝ) (t : ℝ) : ℝ := ∑ i, S.Ev t i * x i

end Model

/-! ## 4.41–4.45: the `α*` parametrisation and invariance of the convex hull -/

/-- (4.41): `θ*ᵖ` is a convex combination of the *initial* estimates.  The
dissertation assumes this at `t = 0` and then uses it at every `t`; that step is
`Hull.hull_invariance` below. -/
structure Hull {d M : ℕ} (S : Model d M) where
  /-- the convex coefficients `α*` -/
  α : Fin (M + 1) → ℝ
  sum_eq_one : ∑ i, α i = 1
  mem_Icc : ∀ i, α i ∈ Set.Icc (0 : ℝ) 1
  /-- (4.41) at `t = 0` -/
  init : ∀ j, ∑ i, S.θ i 0 j * α i = S.θstar j

namespace Hull

variable {d M : ℕ} {S : Model d M} (H : Hull S)

/-- the `α*`-combination of the parametric errors -/
def tha (t : ℝ) : Fin d → ℝ := fun j => ∑ i, S.tht i t j * H.α i

/-- (4.43)/(4.45): `e_{α,f} = ∑ᵢ e_{i,f} α*ᵢ`. -/
def ea (t : ℝ) : ℝ := ∑ i, S.e i t * H.α i

theorem tha_init (j : Fin d) : H.tha 0 j = 0 := by
  have h : ∑ i, S.tht i 0 j * H.α i
      = (∑ i, S.θ i 0 j * H.α i) - S.θstar j * ∑ i, H.α i := by
    simp only [Model.tht, Pi.sub_apply, Finset.mul_sum, ← Finset.sum_sub_distrib]
    exact Finset.sum_congr rfl fun i _ => by ring
  rw [tha, h, H.sum_eq_one, H.init j]
  ring

theorem ea_eq_dot_tha (t : ℝ) : H.ea t = H.tha t ⬝ᵥ S.φ t := by
  simp only [ea, tha, dotProduct, Finset.sum_mul]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [S.e_eq_dot_tht i t]
  simp only [dotProduct, Finset.sum_mul]
  exact Finset.sum_congr rfl fun j _ => by ring

theorem tha_law (j : Fin d) :
    Deriv (fun t => H.tha t j) (fun t => -(S.γ j * (H.ea t / S.msq t) * S.φ t j)) := by
  have key : Deriv (fun t => ∑ i, S.tht i t j * H.α i)
      (fun t => ∑ i, -(S.γ j * S.eps i t * S.φ t j) * H.α i) :=
    Deriv.sum Finset.univ _ _ fun i _ => (S.tht_law i j).mul_const (H.α i)
  refine key.congr (fun _ => rfl) fun t => ?_
  have h : ∀ i, -(S.γ j * S.eps i t * S.φ t j) * H.α i
      = (-(S.γ j * S.φ t j) * (S.msq t)⁻¹) * (S.e i t * H.α i) := by
    intro i
    have hm : S.msq t ≠ 0 := S.msq_ne_zero t
    rw [Model.eps]
    field_simp
  rw [Finset.sum_congr rfl fun i _ => h i, ← Finset.mul_sum]
  have hea : ∑ i, S.e i t * H.α i = H.ea t := rfl
  rw [hea]
  have hm : S.msq t ≠ 0 := S.msq_ne_zero t
  field_simp

/-- **Invariance of the convex hull.**  If `θ*ᵖ` is in the convex hull of the
initial estimates, it stays in the convex hull of the estimates *with the same
coefficients* for every `t ≥ 0`.

This is item 3) of Narendra–Wang–Chen; the dissertation states it without proof
("os parâmetros verdadeiros pertencem ao fecho convexo").  The proof here is a
Lyapunov argument plus the mean value theorem, not an ODE-uniqueness handwave. -/
theorem hull_invariance : ∀ t, 0 ≤ t → ∀ j, H.tha t j = 0 := by
  refine quad_zero (W' := fun t => -(H.ea t / S.msq t * H.ea t)) S.hγ ?_ ?_ H.tha_init
  · exact (S.grad_Wq_deriv H.tha (fun t => H.ea t / S.msq t) H.tha_law).congr
      (fun _ => rfl) fun t => by rw [← H.ea_eq_dot_tha]
  · intro t
    have h1 : 0 < S.msq t := S.msq_pos t
    have h2 : 0 ≤ H.ea t * H.ea t := mul_self_nonneg _
    have h3 : 0 ≤ H.ea t / S.msq t * H.ea t := by
      rw [div_mul_eq_mul_div]
      exact div_nonneg h2 h1.le
    linarith

/-- (4.41) now holds at every instant, not just at `t = 0`. -/
theorem theta_star_in_hull (t : ℝ) (ht : 0 ≤ t) (j : Fin d) :
    ∑ i, S.θ i t j * H.α i = S.θstar j := by
  have h0 := H.hull_invariance t ht j
  have h : ∑ i, S.tht i t j * H.α i
      = (∑ i, S.θ i t j * H.α i) - S.θstar j * ∑ i, H.α i := by
    simp only [Model.tht, Pi.sub_apply, Finset.mul_sum, ← Finset.sum_sub_distrib]
    exact Finset.sum_congr rfl fun i _ => by ring
  rw [tha, h, H.sum_eq_one] at h0
  linarith

/-- **(4.45)**: the `α*`-combination of the identification errors is identically
zero for `t ≥ 0`.  The dissertation only claims `→ 0` as `t → ∞`. -/
theorem ea_zero (t : ℝ) (ht : 0 ≤ t) : H.ea t = 0 := by
  rw [H.ea_eq_dot_tha t]
  unfold dotProduct
  exact Finset.sum_eq_zero fun j _ => by rw [H.hull_invariance t ht j]; ring

/-- **(4.44)**, general form: there is an extra term `θ̃_αᵀ φ̇`. -/
theorem ea_deriv_general :
    Deriv H.ea (fun t => -(H.ea t / S.msq t * S.phiGphi t) + H.tha t ⬝ᵥ S.φ' t) :=
  (S.gen_e_deriv H.tha (fun t => H.ea t / S.msq t) H.tha_law).congr
    (fun t => (H.ea_eq_dot_tha t).symm) fun _ => rfl

/-- **(4.44)**: under hull invariance the extra term vanishes and one recovers
`ė_{α,f} = −(e_{α,f}/m²) φᵀΓφ`. -/
theorem ea_deriv (hz : ∀ t j, H.tha t j = 0) :
    Deriv H.ea (fun t => -(H.ea t / S.msq t * S.phiGphi t)) := by
  refine H.ea_deriv_general.congr (fun _ => rfl) fun t => ?_
  have : H.tha t ⬝ᵥ S.φ' t = 0 := by
    unfold dotProduct
    exact Finset.sum_eq_zero fun j _ => by rw [hz t j]; ring
  rw [this]
  ring

theorem sum_eps_alpha (t : ℝ) : ∑ i, S.eps i t * H.α i = H.ea t / S.msq t := by
  rw [ea, Finset.sum_div]
  exact Finset.sum_congr rfl fun i _ => by rw [Model.eps]; ring

/-- **(4.49)/(4.51)**, exact form: eliminating `α*_N = 1 − ∑_{i<N} α*_i` (4.48)
from `Ē_f ᾱ*_f = ∑ᵢ εᵢ α*ᵢ` (4.46)–(4.47) gives `E_f α*_f = −ε_{N,f}` up to the
residual `e_{α,f}/m²`. -/
theorem E_alpha_star (t : ℝ) :
    ∑ i : Fin M, S.Ev t i * H.α i.castSucc
      = -S.eps (Fin.last M) t + H.ea t / S.msq t := by
  have hsplit : ∑ i, S.eps i t * H.α i
      = (∑ i : Fin M, S.eps i.castSucc t * H.α i.castSucc)
        + S.eps (Fin.last M) t * H.α (Fin.last M) :=
    Fin.sum_univ_castSucc (fun i => S.eps i t * H.α i)
  have hα : ∑ i : Fin M, H.α i.castSucc = 1 - H.α (Fin.last M) := by
    have h := Fin.sum_univ_castSucc H.α
    rw [H.sum_eq_one] at h
    linarith
  have hE : ∑ i : Fin M, S.Ev t i * H.α i.castSucc
      = (∑ i : Fin M, S.eps i.castSucc t * H.α i.castSucc)
        - S.eps (Fin.last M) t * ∑ i : Fin M, H.α i.castSucc := by
    simp only [Model.Ev, Finset.mul_sum, ← Finset.sum_sub_distrib]
    exact Finset.sum_congr rfl fun i _ => by ring
  have h2 := H.sum_eps_alpha t
  rw [hsplit] at h2
  rw [hE, hα]
  linear_combination h2

/-- **(4.51)** proper: for `t ≥ 0` the residual vanishes. -/
theorem E_alpha_star_exact (t : ℝ) (ht : 0 ≤ t) :
    ∑ i : Fin M, S.Ev t i * H.α i.castSucc = -S.eps (Fin.last M) t := by
  rw [H.E_alpha_star t, H.ea_zero t ht, zero_div, add_zero]

end Hull

/-! ## 4.52–4.58: conventional second level adaptation -/

/-- (4.52): the conventional second-level adaptive law
`α̇_f = −γ E_fᵀE_f α_f − γ E_fᵀ ε_{N,f}`.  Since `E_f` is a row vector,
`(E_fᵀE_f α_f)ᵢ = Eᵢ (E_f α_f)`. -/
structure SecondLevel {d M : ℕ} {S : Model d M} (H : Hull S) where
  /-- the second-level gain `γ_{n2,f}` -/
  γ₂ : ℝ
  hγ₂ : 0 < γ₂
  /-- `α_f(t) ∈ ℝ^{N−1}` -/
  α : ℝ → Fin M → ℝ
  law : ∀ i, Deriv (fun t => α t i)
    (fun t => -γ₂ * (S.Ev t i * ∑ k, S.Ev t k * α t k)
              - γ₂ * (S.Ev t i * S.eps (Fin.last M) t))

namespace SecondLevel

variable {d M : ℕ} {S : Model d M} {H : Hull S} (L : SecondLevel H)

/-- (4.54): `α̃_f = α_f − α*_f`. -/
def alpt (t : ℝ) (i : Fin M) : ℝ := L.α t i - H.α i.castSucc

/-- `E_f α_f` -/
def Ealp (t : ℝ) : ℝ := ∑ i, S.Ev t i * L.α t i

/-- `E_f α̃_f` -/
def Ealpt (t : ℝ) : ℝ := ∑ i, S.Ev t i * L.alpt t i

theorem Ealp_split (t : ℝ) :
    L.Ealp t = L.Ealpt t + (-S.eps (Fin.last M) t + H.ea t / S.msq t) := by
  rw [← H.E_alpha_star t]
  simp only [Ealp, Ealpt, alpt, ← Finset.sum_add_distrib]
  exact Finset.sum_congr rfl fun i _ => by ring

/-- **(4.55)+(4.56)**: `α̃̇_f = −γ E_fᵀE_f α̃_f − γ E_fᵀ e_{α,f}/m²`. -/
theorem alpt_deriv (i : Fin M) :
    Deriv (fun t => L.alpt t i)
      (fun t => -L.γ₂ * (S.Ev t i * L.Ealpt t)
                - L.γ₂ * (S.Ev t i * (H.ea t / S.msq t))) := by
  refine ((L.law i).sub_const (H.α i.castSucc)).congr (fun _ => rfl) fun t => ?_
  have h : ∑ k, S.Ev t k * L.α t k
      = L.Ealpt t + (-S.eps (Fin.last M) t + H.ea t / S.msq t) := L.Ealp_split t
  rw [h]
  ring

/-! ### 4.57–4.58: Lyapunov analysis

The dissertation's candidate (4.57) is built on the *extended* vector `ᾱ_f`
whose last entry is `1 − 1⃗α_f`, so `ᾱ̃ = [α̃ ; −1⃗α̃]`.  We treat both that
function (`Vb`) and the reduced one used by Narendra–Wang–Chen (`Vr`). -/

/-- The reduced Lyapunov function `V = α̃ᵀα̃/2`.  This is the correct
counterpart of (4.58): it is eq. (24) of Narendra–Wang–Chen. -/
def Vr : ℝ → ℝ := Wq (fun _ : Fin M => 1) L.alpt

theorem Vr_deriv :
    Deriv L.Vr (fun t => -L.γ₂ * (L.Ealpt t * L.Ealpt t)
                        - L.γ₂ * (L.Ealpt t * (H.ea t / S.msq t))) := by
  refine (Wq_hasDeriv L.alpt_deriv).congr (fun _ => rfl) fun t => ?_
  simp only [inv_one, one_mul]
  have h : ∀ i, L.alpt t i *
      (-L.γ₂ * (S.Ev t i * L.Ealpt t) - L.γ₂ * (S.Ev t i * (H.ea t / S.msq t)))
      = (-L.γ₂ * L.Ealpt t - L.γ₂ * (H.ea t / S.msq t)) * (S.Ev t i * L.alpt t i) :=
    fun i => by ring
  rw [Finset.sum_congr rfl fun i _ => h i, ← Finset.mul_sum]
  have h2 : ∑ i, S.Ev t i * L.alpt t i = L.Ealpt t := rfl
  rw [h2]
  ring

/-- With `e_{α,f} = 0` — which holds for `t ≥ 0` by `Hull.ea_zero` — the reduced
Lyapunov function is nonincreasing, so `α̃_f` is bounded.  This is the
qualitative conclusion of Section 4.3. -/
theorem Vr_antitone (h : ∀ t, H.ea t = 0) : Antitone L.Vr :=
  L.Vr_deriv.antitone fun t => by
    have hg := L.hγ₂
    rw [h t, zero_div]
    nlinarith [mul_self_nonneg (L.Ealpt t)]

/-- `1⃗ ⬝ α̃_f`, the extra coordinate of the dissertation's extended vector. -/
def Sb (t : ℝ) : ℝ := ∑ i, L.alpt t i

theorem Sb_deriv :
    Deriv L.Sb (fun t => -L.γ₂ * (S.SE t * L.Ealpt t)
                        - L.γ₂ * (S.SE t * (H.ea t / S.msq t))) := by
  refine (Deriv.sum Finset.univ _ _ fun i (_ : i ∈ Finset.univ) => L.alpt_deriv i).congr
    (fun _ => rfl) fun t => ?_
  have h : ∀ i, -L.γ₂ * (S.Ev t i * L.Ealpt t) - L.γ₂ * (S.Ev t i * (H.ea t / S.msq t))
      = (-L.γ₂ * L.Ealpt t - L.γ₂ * (H.ea t / S.msq t)) * S.Ev t i := fun i => by ring
  rw [Finset.sum_congr rfl fun i _ => h i, ← Finset.mul_sum]
  have h2 : ∑ i, S.Ev t i = S.SE t := rfl
  rw [h2]
  ring

/-- (4.57): the dissertation's own Lyapunov candidate,
`V = ᾱ̃ᵀᾱ̃/2γ` with `ᾱ̃ = [α̃ ; −1⃗α̃]`. -/
def Vb (t : ℝ) : ℝ :=
  (2 * L.γ₂)⁻¹ * ((∑ i, L.alpt t i * L.alpt t i) + L.Sb t * L.Sb t)

/-- **The exact derivative of (4.57)**.

Compare with **(4.58)**, which claims
`V̇ = −N α̃ᵀE ᵀE α̃ − N α̃ᵀEᵀ e_α/m²`.  The cross term `(1⃗α̃)(1⃗Eᵀ)` is *not*
`(N−1)·E α̃`, so the two disagree; see `Vb_deriv_differs_from_4_58` and
`Vb_deriv_can_be_positive`. -/
theorem Vb_deriv :
    Deriv L.Vb (fun t => -((L.Ealpt t + L.Sb t * S.SE t)
                            * (L.Ealpt t + H.ea t / S.msq t))) := by
  have hA : Deriv (fun t => ∑ i, L.alpt t i * L.alpt t i)
      (fun t => ∑ i,
        ((-L.γ₂ * (S.Ev t i * L.Ealpt t) - L.γ₂ * (S.Ev t i * (H.ea t / S.msq t)))
            * L.alpt t i
          + L.alpt t i
            * (-L.γ₂ * (S.Ev t i * L.Ealpt t) - L.γ₂ * (S.Ev t i * (H.ea t / S.msq t))))) :=
    Deriv.sum Finset.univ _ _ fun i _ => (L.alpt_deriv i).mul (L.alpt_deriv i)
  have hB := L.Sb_deriv.mul L.Sb_deriv
  refine (Deriv.const_mul (2 * L.γ₂)⁻¹ (hA.add hB)).congr (fun _ => rfl) fun t => ?_
  have h : ∀ i,
      ((-L.γ₂ * (S.Ev t i * L.Ealpt t) - L.γ₂ * (S.Ev t i * (H.ea t / S.msq t)))
          * L.alpt t i
        + L.alpt t i
          * (-L.γ₂ * (S.Ev t i * L.Ealpt t) - L.γ₂ * (S.Ev t i * (H.ea t / S.msq t))))
      = (-2 * L.γ₂ * (L.Ealpt t + H.ea t / S.msq t)) * (S.Ev t i * L.alpt t i) :=
    fun i => by ring
  rw [Finset.sum_congr rfl fun i _ => h i, ← Finset.mul_sum]
  have h2 : ∑ i, S.Ev t i * L.alpt t i = L.Ealpt t := rfl
  rw [h2]
  have hg : L.γ₂ ≠ 0 := L.hγ₂.ne'
  field_simp
  ring

end SecondLevel

/-! ### The factor `N` of (4.58) does not follow

The two statements below are the Lean version of the Coq counterexamples.  They
are stated first as pure arithmetic on the two rate expressions, and then in the
conditional form that ties them to `SecondLevel.Vb_deriv`. -/

/-- The exact rate of change of the dissertation's `V` (4.57), as a function of
`E α̃`, `1⃗α̃`, `1⃗Eᵀ` and `e_α/m²`; this is the integrand of `Vb_deriv`. -/
def rateExact (Ea Sb SE r : ℝ) : ℝ := -((Ea + Sb * SE) * (Ea + r))

/-- The rate claimed by (4.58): `V̇ = −N (E α̃)² − N (E α̃)(e_α/m²)`. -/
def rate458 (N : ℕ) (Ea r : ℝ) : ℝ := -(N * (Ea * Ea)) - N * (Ea * r)

/-- With `N = 3`, `E α̃ = 1`, `1⃗α̃ = 1⃗Eᵀ = 1`, `e_α = 0` the true rate is `−2`
while (4.58) gives `−3`. -/
theorem rateExact_ne_rate458 : rateExact 1 1 1 0 ≠ rate458 3 1 0 := by
  norm_num [rateExact, rate458]

/-- Worse: the dissertation's `V̇` is **not** negative semi-definite.  With
`E α̃ = 1`, `1⃗α̃ = −2`, `1⃗Eᵀ = 1`, `e_α = 0` it equals `+1 > 0`, so (4.57)+(4.58)
do not establish the boundedness of `α̃_f` claimed on page 66. -/
theorem rateExact_can_be_positive : 0 < rateExact 1 (-2) 1 0 := by
  norm_num [rateExact]

/-- The same counterexample given by explicit vectors rather than by the values
of the three scalars.  With `N = 3` (so `E_f, α̃_f ∈ ℝ²`),

    E_f = (2, −1),   α̃_f = (−1/3, −5/3),   e_α = 0,

one has `E α̃ = 1`, `1⃗α̃ = −2`, `1⃗Eᵀ = 1`, and the exact derivative of the
dissertation's `V` (4.57) is `+1 > 0`, while (4.58) would give `−3`.

This is exactly the witness produced independently by the KeYmaera X port of the
same chapter, so the two formalisations agree on the counterexample. -/
theorem rateExact_witness :
    rateExact (∑ i, (![2, -1] : Fin 2 → ℝ) i * (![-1/3, -5/3] : Fin 2 → ℝ) i)
              (∑ i, (![-1/3, -5/3] : Fin 2 → ℝ) i)
              (∑ i, (![2, -1] : Fin 2 → ℝ) i) 0 = 1 := by
  norm_num [rateExact, Fin.sum_univ_two]

theorem rate458_witness :
    rate458 3 (∑ i, (![2, -1] : Fin 2 → ℝ) i * (![-1/3, -5/3] : Fin 2 → ℝ) i) 0 = -3 := by
  norm_num [rate458, Fin.sum_univ_two]

namespace SecondLevel

variable {d M : ℕ} {S : Model d M} {H : Hull S} (L : SecondLevel H)

/-- The conditional form: at any time where those values occur, the exact
derivative of (4.57) differs from the value claimed by (4.58). -/
theorem Vb_deriv_differs_from_4_58 (t : ℝ) (hM : ((M : ℝ) + 1) = 3)
    (hea : H.ea t = 0) (h1 : L.Ealpt t = 1) (h2 : L.Sb t = 1) (h3 : S.SE t = 1) :
    -((L.Ealpt t + L.Sb t * S.SE t) * (L.Ealpt t + H.ea t / S.msq t))
      ≠ -(((M : ℝ) + 1) * (L.Ealpt t * L.Ealpt t)) := by
  rw [h1, h2, h3, hea, hM]
  norm_num

/-- The conditional form of positivity. -/
theorem Vb_deriv_can_be_positive (t : ℝ) (hea : H.ea t = 0)
    (h1 : L.Ealpt t = 1) (h2 : L.Sb t = -2) (h3 : S.SE t = 1) :
    0 < -((L.Ealpt t + L.Sb t * S.SE t) * (L.Ealpt t + H.ea t / S.msq t)) := by
  rw [h1, h2, h3, hea]
  norm_num

end SecondLevel

/-! ## 4.60–4.69: second level adaptation with a forgetting factor (SLAFF) -/

/-- (4.66)+(4.67): the SLAFF data.  `M_f` and `v_f` are the accumulators of
(4.64)/(4.65), given here by the differential equations (4.66) they satisfy;
`Forgetting.Mf_integrating_factor` shows the two descriptions agree. -/
structure Forgetting {d M : ℕ} {S : Model d M} (H : Hull S) where
  γ₂ : ℝ
  hγ₂ : 0 < γ₂
  /-- the forgetting factor `σ` -/
  σ : ℝ
  hσ : 0 < σ
  /-- `M_f` of (4.65) -/
  Mf : ℝ → Fin M → Fin M → ℝ
  /-- `v_f` of (4.65) -/
  vf : ℝ → Fin M → ℝ
  /-- `α_f(t)` -/
  α : ℝ → Fin M → ℝ
  Mf_init : ∀ i j, Mf 0 i j = 0
  vf_init : ∀ i, vf 0 i = 0
  /-- (4.66): `Ṁ_f = −σM_f + EᵀE` -/
  Mf_law : ∀ i j, Deriv (fun t => Mf t i j) (fun t => -σ * Mf t i j + S.Ev t i * S.Ev t j)
  /-- (4.66): `v̇_f = −σv_f + Eᵀε_N` -/
  vf_law : ∀ i, Deriv (fun t => vf t i)
    (fun t => -σ * vf t i + S.Ev t i * S.eps (Fin.last M) t)
  /-- (4.67): `α̇_f = γ(−M_f α_f − EᵀE α_f − v_f − Eᵀ ε_N)` -/
  law : ∀ i, Deriv (fun t => α t i)
    (fun t => γ₂ * (-(∑ j, Mf t i j * α t j) - S.Ev t i * (∑ k, S.Ev t k * α t k)
                    - vf t i - S.Ev t i * S.eps (Fin.last M) t))

namespace Forgetting

variable {d M : ℕ} {S : Model d M} {H : Hull S} (F : Forgetting H)

/-- **(4.65) ↔ (4.66)**: the integrating-factor identity.  Saying
`M_f(t) = ∫₀ᵗ e^{−σ(t−τ)} E_fᵀE_f dτ` with `M_f(0) = 0` is exactly saying that
`e^{σt} M_f(t)` has derivative `e^{σt} EᵀE`. -/
theorem Mf_integrating_factor (i j : Fin M) :
    Deriv (fun t => Real.exp (F.σ * t) * F.Mf t i j)
      (fun t => Real.exp (F.σ * t) * (S.Ev t i * S.Ev t j)) := by
  refine ((Deriv.exp_linear F.σ).mul (F.Mf_law i j)).congr (fun _ => rfl) fun t => ?_
  ring

/-- **(4.65) ↔ (4.66)** for `v_f`. -/
theorem vf_integrating_factor (i : Fin M) :
    Deriv (fun t => Real.exp (F.σ * t) * F.vf t i)
      (fun t => Real.exp (F.σ * t) * (S.Ev t i * S.eps (Fin.last M) t)) := by
  refine ((Deriv.exp_linear F.σ).mul (F.vf_law i)).congr (fun _ => rfl) fun t => ?_
  ring

/-- the quadratic form `xᵀ M_f x` -/
def MQ (x : Fin M → ℝ) (t : ℝ) : ℝ := ∑ i, x i * ∑ j, F.Mf t i j * x j

theorem MQ_deriv (x : Fin M → ℝ) :
    Deriv (F.MQ x) (fun t => -F.σ * F.MQ x t + S.EX x t * S.EX x t) := by
  have inner : ∀ i, Deriv (fun t => ∑ j, F.Mf t i j * x j)
      (fun t => ∑ j, (-F.σ * F.Mf t i j + S.Ev t i * S.Ev t j) * x j) :=
    fun i => Deriv.sum Finset.univ _ _ fun j _ => (F.Mf_law i j).mul_const (x j)
  have key : Deriv (fun t => ∑ i, x i * ∑ j, F.Mf t i j * x j)
      (fun t => ∑ i, x i * ∑ j, (-F.σ * F.Mf t i j + S.Ev t i * S.Ev t j) * x j) :=
    Deriv.sum Finset.univ _ _ fun i _ => (inner i).const_mul (x i)
  refine key.congr (fun _ => rfl) fun t => ?_
  have hEX : S.EX x t = ∑ j, S.Ev t j * x j := rfl
  have hin : ∀ i, ∑ j, (-F.σ * F.Mf t i j + S.Ev t i * S.Ev t j) * x j
      = -F.σ * (∑ j, F.Mf t i j * x j) + S.Ev t i * S.EX x t := by
    intro i
    rw [hEX, Finset.mul_sum, Finset.mul_sum, ← Finset.sum_add_distrib]
    exact Finset.sum_congr rfl fun j _ => by ring
  have hMQ : F.MQ x t = ∑ i, x i * ∑ j, F.Mf t i j * x j := rfl
  rw [Finset.sum_congr rfl fun i _ => by rw [hin i]]
  have step : ∑ i, x i * (-F.σ * (∑ j, F.Mf t i j * x j) + S.Ev t i * S.EX x t)
      = (∑ i, -F.σ * (x i * ∑ j, F.Mf t i j * x j)) + ∑ i, (S.Ev t i * x i) * S.EX x t := by
    rw [← Finset.sum_add_distrib]
    exact Finset.sum_congr rfl fun i _ => by ring
  rw [step, ← Finset.mul_sum, ← Finset.sum_mul, ← hMQ, ← hEX]

/-- **`M_f ⪰ 0`** for all `t ≥ 0`.  This is what makes the quadratic term of
(4.69) sign definite; the dissertation asserts it implicitly by writing `M_f` as
a convolution integral of `EᵀE`. -/
theorem Mf_psd (x : Fin M → ℝ) (t : ℝ) (ht : 0 ≤ t) : 0 ≤ F.MQ x t := by
  have hexp : Deriv (fun t => Real.exp (F.σ * t) * F.MQ x t)
      (fun t => Real.exp (F.σ * t) * (S.EX x t * S.EX x t)) := by
    refine ((Deriv.exp_linear F.σ).mul (F.MQ_deriv x)).congr (fun _ => rfl) fun t => ?_
    ring
  have h0 : F.MQ x 0 = 0 := by
    refine Finset.sum_eq_zero fun i _ => ?_
    rw [Finset.sum_eq_zero fun j _ => by rw [F.Mf_init i j]; ring]
    ring
  have hmono : Real.exp (F.σ * 0) * F.MQ x 0 ≤ Real.exp (F.σ * t) * F.MQ x t :=
    hexp.monotone (fun t => mul_nonneg (Real.exp_pos _).le (mul_self_nonneg _)) ht
  rw [h0, mul_zero] at hmono
  have hp := Real.exp_pos (F.σ * t)
  nlinarith

/-- `α̃_f = α_f − α*_f` for the SLAFF law -/
def alpt (t : ℝ) (i : Fin M) : ℝ := F.α t i - H.α i.castSucc

/-- `E_f α_f` -/
def Ealp (t : ℝ) : ℝ := ∑ i, S.Ev t i * F.α t i

/-- `E_f α̃_f` -/
def Ealpt (t : ℝ) : ℝ := ∑ i, S.Ev t i * F.alpt t i

/-- the residual driven by `e_{α,f}`: `M_f α*_f + v_f`.

**Equation (4.69) writes only `−N α̃ᵀ M_f α*_f`**, omitting `v_f`; the correct
residual mixes both, because `Eᵀ(E α*_f + ε_{N,f}) = Eᵀ e_α/m²`. -/
def qres (t : ℝ) (i : Fin M) : ℝ := (∑ j, F.Mf t i j * H.α j.castSucc) + F.vf t i

theorem Ealp_split (t : ℝ) :
    F.Ealp t = F.Ealpt t + (-S.eps (Fin.last M) t + H.ea t / S.msq t) := by
  rw [← H.E_alpha_star t]
  simp only [Ealp, Ealpt, alpt, ← Finset.sum_add_distrib]
  exact Finset.sum_congr rfl fun i _ => by ring

theorem Mf_alp_split (t : ℝ) (i : Fin M) :
    ∑ j, F.Mf t i j * F.α t j
      = (∑ j, F.Mf t i j * F.alpt t j) + ∑ j, F.Mf t i j * H.α j.castSucc := by
  rw [← Finset.sum_add_distrib]
  exact Finset.sum_congr rfl fun j _ => by rw [alpt]; ring

/-- The SLAFF parametric-error dynamics — the correct counterpart of the step
between (4.67) and (4.69). -/
theorem alpt_deriv (i : Fin M) :
    Deriv (fun t => F.alpt t i)
      (fun t => F.γ₂ * (-(∑ j, F.Mf t i j * F.alpt t j)
                        - S.Ev t i * F.Ealpt t
                        - S.Ev t i * (H.ea t / S.msq t)
                        - F.qres t i)) := by
  refine ((F.law i).sub_const (H.α i.castSucc)).congr (fun _ => rfl) fun t => ?_
  have h1 : ∑ k, S.Ev t k * F.α t k
      = F.Ealpt t + (-S.eps (Fin.last M) t + H.ea t / S.msq t) := F.Ealp_split t
  have h2 := F.Mf_alp_split t i
  rw [h1, h2, qres]
  ring

theorem qres_deriv (i : Fin M) :
    Deriv (fun t => F.qres t i)
      (fun t => -F.σ * F.qres t i + S.Ev t i * (H.ea t / S.msq t)) := by
  have hM : Deriv (fun t => ∑ j, F.Mf t i j * H.α j.castSucc)
      (fun t => ∑ j, (-F.σ * F.Mf t i j + S.Ev t i * S.Ev t j) * H.α j.castSucc) :=
    Deriv.sum Finset.univ _ _ fun j _ => (F.Mf_law i j).mul_const (H.α j.castSucc)
  refine (hM.add (F.vf_law i)).congr (fun _ => rfl) fun t => ?_
  have hsum : ∑ j, (-F.σ * F.Mf t i j + S.Ev t i * S.Ev t j) * H.α j.castSucc
      = -F.σ * (∑ j, F.Mf t i j * H.α j.castSucc)
        + S.Ev t i * ∑ j, S.Ev t j * H.α j.castSucc := by
    rw [Finset.mul_sum, Finset.mul_sum, ← Finset.sum_add_distrib]
    exact Finset.sum_congr rfl fun j _ => by ring
  rw [hsum, H.E_alpha_star t, qres]
  ring

/-- **The residual `M_f α*_f + v_f` vanishes identically** once `θ*ᵖ` is in the
convex hull, so the sign-indefinite term of (4.69) disappears. -/
theorem qres_zero (hea : ∀ t, H.ea t = 0) (t : ℝ) (ht : 0 ≤ t) (i : Fin M) :
    F.qres t i = 0 := by
  refine quad_zero (c := fun _ : Fin M => 1) (T := F.qres)
    (W' := fun t => -F.σ * ∑ i, F.qres t i * F.qres t i)
    (fun _ => one_pos) ?_ ?_ ?_ t ht i
  · refine (Wq_hasDeriv F.qres_deriv).congr (fun _ => rfl) fun t => ?_
    rw [hea t, zero_div]
    simp only [inv_one, one_mul]
    have h : ∀ i, F.qres t i * (-F.σ * F.qres t i + S.Ev t i * 0)
        = -F.σ * (F.qres t i * F.qres t i) := fun i => by ring
    rw [Finset.sum_congr rfl fun i _ => h i, ← Finset.mul_sum]
  · intro t
    have h : 0 ≤ ∑ i, F.qres t i * F.qres t i :=
      Finset.sum_nonneg fun i _ => mul_self_nonneg _
    have := F.hσ
    nlinarith
  · intro i
    rw [qres, Finset.sum_eq_zero fun j _ => by rw [F.Mf_init i j]; ring, F.vf_init i]
    ring

/-- (4.68): the same Lyapunov candidate as (4.57), in reduced form. -/
def VrF : ℝ → ℝ := Wq (fun _ : Fin M => 1) F.alpt

/-- **The exact derivative of (4.68)**.

Compare with **(4.69)**, which claims `V̇ = −N α̃ᵀ M_f α̃ − N (E α̃)² −
N α̃ᵀ M_f α*_f`.  Besides the spurious factor `N` (same issue as (4.58)), the
residual term is `M_f α*_f + v_f`, not `M_f α*_f`: `v_f` is missing.  The
dissertation's own justification one line later,
`N α̃ᵀ M_f α*_f = N ∫ e^{−σ(t−τ)} Eᵀ e_α dτ`, is the value of `M_f α*_f + v_f`,
so the intent is right and only the written expression is incomplete. -/
theorem VrF_deriv :
    Deriv F.VrF
      (fun t => F.γ₂ * (-(∑ i, F.alpt t i * ∑ j, F.Mf t i j * F.alpt t j)
                        - F.Ealpt t * F.Ealpt t
                        - F.Ealpt t * (H.ea t / S.msq t)
                        - ∑ i, F.alpt t i * F.qres t i)) := by
  refine (Wq_hasDeriv F.alpt_deriv).congr (fun _ => rfl) fun t => ?_
  simp only [inv_one, one_mul]
  have h : ∀ i, F.alpt t i *
      (F.γ₂ * (-(∑ j, F.Mf t i j * F.alpt t j) - S.Ev t i * F.Ealpt t
               - S.Ev t i * (H.ea t / S.msq t) - F.qres t i))
      = -F.γ₂ * (F.alpt t i * ∑ j, F.Mf t i j * F.alpt t j)
        + -F.γ₂ * (F.alpt t i * F.qres t i)
        + (F.γ₂ * (-F.Ealpt t - H.ea t / S.msq t)) * (S.Ev t i * F.alpt t i) :=
    fun i => by ring
  rw [Finset.sum_congr rfl fun i _ => h i]
  rw [Finset.sum_add_distrib, Finset.sum_add_distrib,
    ← Finset.mul_sum, ← Finset.mul_sum, ← Finset.mul_sum]
  have h2 : ∑ i, S.Ev t i * F.alpt t i = F.Ealpt t := rfl
  rw [h2]
  ring

/-- **What (4.69) intends**: with `e_{α,f} = 0` (i.e. for `t ≥ 0`, by
`Hull.ea_zero`) the derivative of (4.68) is negative semi-definite, because the
quadratic form in `M_f` is PSD (`Mf_psd`) and the residual vanishes
(`qres_zero`). -/
theorem VrF_nonpos (hea : ∀ t, H.ea t = 0) (t : ℝ) (ht : 0 ≤ t) :
    F.γ₂ * (-(∑ i, F.alpt t i * ∑ j, F.Mf t i j * F.alpt t j)
            - F.Ealpt t * F.Ealpt t
            - F.Ealpt t * (H.ea t / S.msq t)
            - ∑ i, F.alpt t i * F.qres t i) ≤ 0 := by
  have hq : ∑ i, F.alpt t i * F.qres t i = 0 :=
    Finset.sum_eq_zero fun i _ => by rw [F.qres_zero hea t ht i]; ring
  have hpsd : 0 ≤ ∑ i, F.alpt t i * ∑ j, F.Mf t i j * F.alpt t j :=
    F.Mf_psd (F.alpt t) t ht
  have hg := F.hγ₂
  rw [hea t, zero_div, hq]
  nlinarith [mul_self_nonneg (F.Ealpt t)]

end Forgetting

end SLA
