
%simulação 1, referente ao artigo
disp('simulação 1, referente ao artigo enviado para o CBA')
SIM1 = struct('stoptime',18, 'h',1e-3, 'modelos',[-4 -3 8;               ...
       -5 -2 -4], 'planta',[2.3; -3.6], 'modelo_de_referencia',          ...
       [-4 -4], 'cond_iniciais_p',[0; 0],'cond_iniciais_m',[0.2; 0.3],   ...
       'cond_iniciais_i',[0 0 0 ;0 0 0], 'alfa0',[0 1],'referencia',5,   ...
       'Q',[1e4 0;0 1e4],'gamma',10,'P',[100 0;0 100],'cor',0.2,'nframes',  ...
       40);
disp('trajetórias das estimativas dos parâmetros');
anim_trajetorias(@L2AA,SIM1);

disp('variáveis de interesse usando adaptação convencional')
pause
plot_adap_figures(L1A(SIM1));
disp('variáveis de interesse usando adaptação de segundo nível')
pause

plot_adap_figures(L2AA(SIM1));

%simulação 2, referente ao artigo
SIM2 = struct('stoptime',90, 'h',5e-2, 'modelos',[-4 -3 8;               ...
       -5 -2 -4], 'planta',[2.3; -3.6], 'modelo_de_referencia',          ...
       [-4 -4], 'cond_iniciais_p',[0; 0],'cond_iniciais_m',[0.2; 0.3],   ...
       'cond_iniciais_i',[0 0 0 ;0 0 0], 'alfa0',[0 1],'referencia',5,   ...
       'Q',[1e4 0;0 1e4],'gamma',100,'P',[4 0;0 4],'cor',0.2,'nframes',  ...
       40);