function estrutura = make_struct(x_p,x_m,eta,theta_p_estimativa,norm_2_e_o,  ...
                                 e_o,u, alfa_barra, r, modelo_de_referencia, ...
                                 planta, theta_BARRA, modelos,tempo,endk)

   estrutura = convert_names_to_fields ...
        (x_p,x_m,eta,theta_p_estimativa,norm_2_e_o,  ...
         e_o,u, alfa_barra, r, modelo_de_referencia, ...
         planta, theta_BARRA, modelos,tempo,endk);
                          
                             
                             
end