function [hat_a_p_n2, hat_k_p_n2,y,y_m,u,tempo_1] = L2A_3M_Filtragem_O1(t,h)

endk = t/h;
y(1) = 0.2;
y_m(1) = 0;
z_hat_1(1) = 0;
z_hat_2(1) = 0;
z_hat_3(1) = 0;
a_p = 1.5;
k_p = 3;
k_m = 5;
a_m = 5;
hat_a_p_1(1) = 0.5;
hat_k_p_1(1) = 1;
hat_a_p_2(1) = 0.5;
hat_k_p_2(1) = 11;
hat_a_p_3(1) = 7;
hat_k_p_3(1) = 1;
alfa_1(1) = 0.5;
alfa_2(1) = 0.5;
alfa_3(1) = 0;
alfa(:,1) = [alfa_1(1); alfa_2(1)];
phi_1(1) = 0;
phi_2(1) = 0;
lambda=4;
hat_a_p_n2(1) = 0.5;
hat_k_p_n2(1) = 6;
for k=1: endk
   r(k) = 1;
   k_1 = (hat_a_p_n2(k)-a_m)/hat_k_p_n2(k);
   k_2 = k_m/hat_k_p_n2(k);
   u(k) = k_1*y(k)+k_2*r(k);
   tempo(k) = h*k;
   tempo_1(k+1) = h+h*k;
   dot_y(k) = -a_p*y(k) + k_p*u(k);
   y(k+1) = y(k) + h*dot_y(k);
   dot_y_m(k) = -a_m*y_m(k) + k_m*r(k);
   y_m(k+1) = y_m(k) + h*dot_y_m(k);
   e_o(k) = y(k)-y_m(k);
   dot_phi_1(k) = -lambda*phi_1(k) + y(k);
   phi_1(k+1) = phi_1(k) + h*dot_phi_1(k);
   dot_phi_2(k) = -lambda*phi_2(k) + u(k);
   phi_2(k+1) = phi_2(k) + h*dot_phi_2(k);
   z(k) = y(k) - lambda*phi_1(k);
  %z(k) = -a_p*phi_1(k)+k_p*phi_2(k);
  z_hat_1(k) = -phi_1(k)*hat_a_p_1(k) + phi_2(k)*hat_k_p_1(k);
  z_hat_2(k) = -phi_1(k)*hat_a_p_2(k) + phi_2(k)*hat_k_p_2(k);
  z_hat_3(k) = -phi_1(k)*hat_a_p_3(k) + phi_2(k)*hat_k_p_3(k);
   e_1_f(k) = z_hat_1(k) - z(k);
   e_2_f(k) = z_hat_2(k) - z(k);
   e_3_f(k) = z_hat_3(k) - z(k);
   dot_hat_a_p_1(k) = e_1_f(k)*y(k);
   hat_a_p_1(k+1) = hat_a_p_1(k) + h*dot_hat_a_p_1(k);
   dot_hat_a_p_2(k) = e_2_f(k)*y(k);
   hat_a_p_2(k+1) = hat_a_p_2(k) + h*dot_hat_a_p_2(k);
   dot_hat_a_p_3(k) = e_3_f(k)*y(k);
   hat_a_p_3(k+1) = hat_a_p_3(k) + h*dot_hat_a_p_3(k);
   dot_hat_k_p_1(k) = -e_1_f(k)*u(k);
   hat_k_p_1(k+1) = hat_k_p_1(k) + h*dot_hat_k_p_1(k);
   dot_hat_k_p_2(k) = -e_2_f(k)*u(k);
   hat_k_p_2(k+1) = hat_k_p_2(k) + h*dot_hat_k_p_2(k);
   dot_hat_k_p_3(k) = -e_3_f(k)*u(k);
   hat_k_p_3(k+1) = hat_k_p_3(k) + h*dot_hat_k_p_3(k);  
   E_f(1,:,k) = [e_1_f(k)-e_3_f(k) e_2_f(k)-e_3_f(k)];
   dot_alfa(:,k) = (-E_f(1,:,k)'*E_f(1,:,k)*alfa(:,k) - E_f(1,:,k)'*e_3_f(k))';
   alfa(:,k+1) = alfa(:,k) + h*dot_alfa(:,k);
   alfa_1(k+1) = alfa(1,k+1);
   alfa_2(k+1) = alfa(2,k+1);
   alfa_3(k+1) = 1-alfa_1(k+1)-alfa_2(k+1);
   hat_k_p_n2(k+1) = alfa_1(k+1)*hat_k_p_1(k+1)+alfa_2(k+1)*hat_k_p_2(k+1)+alfa_3(k+1)*hat_k_p_3(k+1);
   hat_a_p_n2(k+1) = alfa_1(k+1)*hat_a_p_1(k+1)+alfa_2(k+1)*hat_a_p_2(k+1)+alfa_3(k+1)*hat_a_p_3(k+1);
   
end

end